### ISSUE TITLE
oracle: Insecure design for the monitoring user/password?

### ISSUE THREAD

**Issue by krig** [ClusterLabs/resource-agents#1030]
The oracle agent has the `monuser` and `monpassword` parameters which default to `OCFMON` / `OCFMON` respectively. If the monuser doesn't already exist, the agent will automatically create it and set the password in the start action.

So someone unaware of this who doesn't configure or precreate the `monuser` will get a OCFMON user with password "OCFMON" created in their database, it seems.

That seems horribly insecure!

The question is what the right fix is. Should there just not be any default values for monuser and monpassword? Then if a monitor action is configured, the validate action would check that they have been configured.

**Comment by oalbrigt** [comment]
I think the best way would be to leave the defaults as is (to avoid issues for users upgrading resource-agents) and replace the automatic creation with error if the user/pass is incorrect/doesnt exist.

**Comment by krig** [comment]
Yeah, that sounds better.

**Comment by dmuhamedagic** [comment]
On Mon, Aug 28, 2017 at 08:02:30AM +0000, Kristoffer Grönlund wrote:
> The oracle agent has the `monuser` and `monpassword` parameters which default to `OCFMON` / `OCFMON` respectively. If the monuser doesn't already exist, the agent will automatically create it and set the password in the start action.
> 
> So someone unaware of this who doesn't configure or precreate the `monuser` will get a OCFMON user with password "OCFMON" created in their database, it seems.
> 
> That seems horribly insecure!
> 
> The question is what the right fix is. Should there just not be any default values for monuser and monpassword? Then if a monitor action is configured, the validate action would check that they have been configured.

A bit of history: it was initially the sqldba user which is
passwordless if run as root. However, every connection would be
logged which resulted in rather big logs, hence monuser got
introduced. It was necessary to create it automatically as
otherwise, on upgrade, the monitor op would fail. This user is
granted select only on one system table, so it shouldn't pose a
security risk.

**Comment by krig** [comment]
Aha, I see.

Hmm. I guess at this point, making it an error instead of automatic should be OK then? Since anyone upgrading would already have the user, and anyone installing fresh would then have to create it.

On the other hand I can see some potential for creating security holes when introducing a human into the mix, since the admin would need to create the user with the right restrictions and so on. Not sure what the best thing is, here, actually.

**Comment by dmuhamedagic** [comment]
On Wed, Aug 30, 2017 at 08:36:17PM +0000, Kristoffer Grönlund wrote:
> Hmm. I guess at this point, making it an error instead of automatic should be OK then?

Yes.

> Since anyone upgrading would already have the user, and anyone installing fresh would then have to create it.
> 
> On the other hand I can see some potential for creating security holes when introducing a human into the mix, since the admin would need to create the user with the right restrictions and so on. Not sure what the best thing is, here, actually.

My best guess: just leave it as is :) If anybody finds this
insecure, they'll update there cluster configuration accordingly.
This is not a default password on a home router, after all.

**Comment by oalbrigt** [comment]
Closing. Changing this will break existing configurations, and users can set another password if it isnt secure enough for their use.

**Comment by jsegitz** [comment]
I disagree with this. Users will very likely use the default, especially it it just works(tm). The privileges granted to the user are limited, but it allows connecting to the database in the first place and therefor might be used in an attack chain. 

My suggestion would be to try the static credentials to prevent breaking old setups. For new setups the user should get a random password that is saved on the filesystem (in secure manner).

**Comment by oalbrigt** [comment]
PR by @nick-wang has been merged, which only fails with ERR_CONFIGURED for new setups (where the user doesnt already exist).

**Comment by jsegitz** [comment]
He just told me, thank you for merging this quickly

**Comment by oalbrigt** [comment]
No problem.

**Comment by nick-wang** [comment]
@jsegitz @oalbrigt Thanks a lot for the help and review!
