### ISSUE TITLE
pgsql: unable to use replication slots with restart_on_promote=true

### ISSUE THREAD

**Issue by covin** [ClusterLabs/resource-agents#1056]
As of commit 7052fcf06 replication slots are created on `promote` and deleted on every start. With `restart_on_promote=true` the new slots are going to be deleted right after their creation.

In function `pgsql_real_start()`:
https://github.com/ClusterLabs/resource-agents/blob/4a3326643bc4b45520c525c0094ac98a9746da6a/heartbeat/pgsql#L621-L623

In function `pgsql_promote()`:
https://github.com/ClusterLabs/resource-agents/blob/4a3326643bc4b45520c525c0094ac98a9746da6a/heartbeat/pgsql#L692-L706

**Comment by gdecicco** [comment]
This bug was briefly discussed in the pull request https://github.com/ClusterLabs/resource-agents/pull/956#issuecomment-329912792
