### ISSUE TITLE
Avoid deprecated Pacemaker tool options

### ISSUE THREAD

**Issue by kgaillot** [ClusterLabs/resource-agents#1077]
Some resource agents use deprecated options to Pacemaker command-line tools. These will not go away anytime soon (they will be kept in Pacemaker 2.0), but we should fix them so they can go away in the future.

* crm_resource:
** replace -H with -N

* crm_attribute, crm_master, crm_standby, crm_failcount:
** replace --get-value with -G
** replace --node-uname with -N
** replace -Q with -q

**Comment by kgaillot** [comment]
Also for crm_attribute and friends:
* Replace --attr-name with -n

**Comment by oalbrigt** [comment]
https://github.com/ClusterLabs/resource-agents/pull/1090

**Comment by kgaillot** [comment]
Looks like the only remaining use of the above is:

* heartbeat/conntrackd: crm_master -Q  (-> -q)

But I'll tack on one more :)

* crm_mon: use `--output-as=xml` instead of `-X` or `--as-xml` (pgsql and redis check the feature set to determine which option to use, but rabbitmq-cluster doesn't, and galera does so in some but not all calls)
