### ISSUE TITLE
build should not require internet / network connectivity

### ISSUE THREAD

**Issue by fabbione** [ClusterLabs/resource-agents#1122]
OCF_ROOT=. OCF_FUNCTIONS_DIR=../../heartbeat ../../heartbeat/AudibleAlarm meta-data > metadata-AudibleAlarm.xml
/usr/bin/xsltproc --novalid \
--stringparam package resource-agents \
--stringparam version 4.1.1 \
--output ocf_heartbeat_AudibleAlarm.xml \
./ra2refentry.xsl metadata-AudibleAlarm.xml
/usr/bin/xsltproc \
--xinclude \
http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ocf_heartbeat_AudibleAlarm.xml
error : Operation in progress
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/table.xsl"
compilation error: file http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl line 44 element include
xsl:include : unable to load http://docbook.sourceforge.net/release/xsl/current/html/table.xsl

while in general this is not an issue, it should be possible to build ras without network.

There are of course different options to solve this problem. for example:

1) use distro packaged versions of those files if internet is not available
2) ship those files inside resource-agents as fallback

So ideally the build system would attempt to download them fresh to use a local latest copy, and failing that, use the fallback.

also accessing internet many times for each agent seems aggressive to me :-) cache and live happily ever after (makes it easier to avoid intermittent failures while the pipes are busy)

**Comment by krig** [comment]
We're building the resource agents on OBS VMs that don't have internet access, so this is definitely not a strict requirement. I wonder if xsltproc runs to the internet if the files aren't found locally?

**Comment by fabbione** [comment]
I am no way an xsltproc expert, but the invocation seems pretty straight forward to me (accessing an internet URL). In this case the network was flaky and slow, hence timeout and failures. Tho I can´t firewall everything to build ras :-) Perhaps the invocation can be fixed to call into internet if local is not available.

**Comment by krig** [comment]
Yeah, I inherited the build setup here so I'm not sure what exactly is going on with xsltproc. Maybe we have a patched version..? Either way, the build systems we use don't have any network at all, so it is definitely possible to avoid the network access. But I'll have to dig into the internals of the build here to figure out how that works.

**Comment by oalbrigt** [comment]
Yeah, it works with local files as well, when the STYLESHEET_PREFIX is overridden, so I'll add some logic to use those when present (docbook-style-xsl in Fedora and RHEL).

**Comment by oalbrigt** [comment]
https://github.com/ClusterLabs/resource-agents/pull/1126
