### ISSUE TITLE
Centos 7 make rpm fails

### ISSUE THREAD

**Issue by ntt1985** [ClusterLabs/resource-agents#1137]
Hello, I'm trying to generate an rpm with rpmbuild but if fails with this error:
error: Failed build dependencies:
	cluster-glue-libs-devel is needed by resource-agents-4.1.1-1.16.50da.el7.centos.x86_64

The problem is that cluster-glue-libs-devel seems to be unavailable on centos7 (it exists for el6). Someone can give me some advice about this problem?
Thank you

**Comment by oalbrigt** [comment]
The spec-file in this PR should solve this issue: https://github.com/ClusterLabs/resource-agents/pull/1123

**Comment by ntt1985** [comment]
I tried to substitute resource-agents.spec.in with the file you've posted in issue #1123 but it doesn't work. I have an error:
Processing files: resource-agents-3.9.6-1.el7.centos.x86_64
error: File not found: /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/resource-agents/metadata.rng
error: File not found: /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/lib/systemd/system/resource-agents-deps.target
error: File not found: /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/lib/tmpfiles.d/resource-agents.conf
error: File not found: /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/resource-agents/ocft/helpers.sh
error: File not found: /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/resource-agents/ocft/runocft
error: File not found: /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/resource-agents/ocft/runocft.prereq
Executing(%doc): /bin/sh -e /var/tmp/rpm-tmp.gKByPz
+ umask 022
+ cd /root/resource-agents
+ cd resource-agents-3.9.6
+ DOCDIR=/root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/doc/resource-agents-3.9.6
+ export DOCDIR
+ /usr/bin/mkdir -p /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/doc/resource-agents-3.9.6
+ cp -pr AUTHORS /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/doc/resource-agents-3.9.6
+ cp -pr COPYING /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/doc/resource-agents-3.9.6
+ cp -pr COPYING.GPLv3 /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/doc/resource-agents-3.9.6
+ cp -pr COPYING.LGPL /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/doc/resource-agents-3.9.6
+ cp -pr ChangeLog /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/doc/resource-agents-3.9.6
+ cp -pr 'heartbeat/README.*' /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/doc/resource-agents-3.9.6
cp: cannot stat 'heartbeat/README.*': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.gKByPz (%doc)


RPM build errors:
    File not found: /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/resource-agents/metadata.rng
    File not found: /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/lib/systemd/system/resource-agents-deps.target
    File not found: /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/lib/tmpfiles.d/resource-agents.conf
    File not found: /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/resource-agents/ocft/helpers.sh
    File not found: /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/resource-agents/ocft/runocft
    File not found: /root/rpmbuild/BUILDROOT/resource-agents-3.9.6-1.el7.centos.x86_64/usr/share/resource-agents/ocft/runocft.prereq
    Bad exit status from /var/tmp/rpm-tmp.gKByPz (%doc)
make: *** [rpm] Error 1
[root@pcmk1

I'm not an expert, so probably I did something wrong, can you help me?
Why it tries to build version 3.9.6 if I did git clone from master?

Thank you

**Comment by oalbrigt** [comment]
It sounds like your tree isnt up-to-date. Try running "git pull" first.

**Comment by ntt1985** [comment]
Ok, I cloned again the repo. Now I have this error:

/usr/bin/install: cannot stat './ocf_heartbeat_gcp-vpc-move-ip.7': No such file or directory
gmake[5]: *** [install-man7] Error 1
gmake[5]: Leaving directory `/root/resource-agents/resource-agents-4.1.1.16-50da-dirty/doc/man'
gmake[4]: *** [install-am] Error 2
gmake[4]: Leaving directory `/root/resource-agents/resource-agents-4.1.1.16-50da-dirty/doc/man'
gmake[3]: *** [install-recursive] Error 1
gmake[3]: Leaving directory `/root/resource-agents/resource-agents-4.1.1.16-50da-dirty/doc'
gmake[2]: *** [install-recursive] Error 1
gmake[2]: Leaving directory `/root/resource-agents/resource-agents-4.1.1.16-50da-dirty'
make[1]: *** [install] Error 2
make[1]: Leaving directory `/root/resource-agents/resource-agents-4.1.1.16-50da-dirty'
error: Bad exit status from /var/tmp/rpm-tmp.GbYh19 (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.GbYh19 (%install)
make: *** [rpm] Error 1
[root@pcmk1 resource-agents]#

**Comment by oalbrigt** [comment]
Nice catch. I've made a PR to fix this: https://github.com/ClusterLabs/resource-agents/pull/1138

**Comment by ntt1985** [comment]
I tried to fix but I have this error:
cp: cannot stat 'heartbeat/README.*': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.SONcjT (%doc)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.SONcjT (%doc)
make: *** [rpm] Error 1

**Comment by oalbrigt** [comment]
That's strange. I dont get that issue, and those files are in the master-branch of the repository.

**Comment by ntt1985** [comment]
Yes, it tries to copy heartbeat/README.* in <build_root_rpm_dir>/usr/share/doc/resource-agents-4.1.1 but
+ cp -pr 'heartbeat/README.*' /root/rpmbuild/BUILDROOT/resource-agents-4.1.1-1.16.50da.dirty.el7.centos.x86_64/usr/share/doc/resource-agents-4.1.1
cp: cannot stat 'heartbeat/README.*': No such file or directory

I confirm that heartbeat/README.galera and heartbeat/README.mariadb.md are present in sources. Any ideas?

Thank you

**Comment by oalbrigt** [comment]
You probably need to use heartbeat/Makefile.am from the same PR: https://github.com/ClusterLabs/resource-agents/pull/1123/files#diff-75f1667a928ed17529a43cddda57437b

Run "./autogen.sh && ./configure" after patching Makefile.am to make "make rpm" work correctly.

**Comment by oalbrigt** [comment]
Try "git fetch origin pull/1123/head:pr-1123" and then "git checkout pr-1123" and then run ./autogen.sh and ./configure again before "make rpm".

**Comment by ntt1985** [comment]
Ok, I confirm that the problem is solved. Thank you

**Comment by oalbrigt** [comment]
No problem.
