### ISSUE TITLE
Make IPsrcaddr more flexible

### ISSUE THREAD

**Issue by incognico** [ClusterLabs/resource-agents#1217]
The IPsrcaddr agent can set the source IP for the default route but not for any other routes.

For example I have a vlan1 for WAN connectivity but the default route points somewhere else (and should not be modified). The active cluster node should change the vlan1 route to include the vlan1 VIP as src addr. IPsrcaddr can't do that.

Or am I just looking at the wrong place? Maybe some other resource agent can accomplish that? Suggestions are welcome.

**Comment by nrwahl2** [comment]
@incognico Is this fixed from your perspective in the current version? We've added options to specify destination and table.

**Comment by Rico29** [comment]
Hello
It does not seem to work correctly with the last version of IPsrcaddr.
With two IPsrcaddr resources, the last one which is ran changes the source address of the default gateway, even if it's not part of the same network. See example below : 

root@cluster1:~# ip r l
default via 192.168.222.1 dev ens18 src **192.168.222.93** onlink 
10.9.0.0/24 via 10.9.0.2 dev tun0 
10.9.0.2 dev tun0 proto kernel scope link src 10.9.0.1 
192.168.111.0/24 dev ens19 scope link 
192.168.222.0/24 dev ens18 scope link src 192.168.222.93 


root@cluster1:~# crm configure show
node 1: cluster1 \
        attributes standby=off
node 2: cluster2
primitive email_alert MailTo \
        params email=root \
        params subject="[ATTENTION] Freepbx HA cluster"
primitive iproute_linkt Route \
        params destination="185.176.177.32/27" gateway=192.168.222.4 source=192.168.222.93 family=ip4 \
        op monitor interval=20s \
        meta target-role=Stopped
primitive shared_ip_data IPaddr2 \
        params ip=192.168.222.93 cidr_netmask=24 \
        op monitor interval=60s \
        meta migration-threshold=1 failure-timeout=60s
primitive shared_ip_test IPaddr2 \
        params ip=192.168.111.254 cidr_netmask=24 \
        op monitor interval=60s \
        meta migration-threshold=1 failure-timeout=60s target-role=Started
primitive srcaddr_ip_data IPsrcaddr \
        params ipaddress=192.168.222.93 \
        op monitor interval=10 \
        op_params failure-timeout=60s \
        meta target-role=Started
primitive srcaddr_ip_test IPsrcaddr \
        params ipaddress=192.168.111.254 \
        op monitor interval=10 \
        op_params failure-timeout=60s \
        meta target-role=Stopped
group freepbx shared_ip_data srcaddr_ip_data shared_ip_test srcaddr_ip_test iproute_linkt
location cli-prefer-freepbx freepbx role=Started inf: cluster1
location freepbx-pabx1 freepbx 100: cluster1
property cib-bootstrap-options: \
        have-watchdog=false \
        dc-version=2.0.1-9e909a5bdd \
        cluster-infrastructure=corosync \
        cluster-name=debian \
        stonith-enabled=false \
        no-quorum-policy=ignore \
        resource-stickiness=infinity \
        cluster-recheck-interval=10s \
        pe-error-series-max=500 \
        pe-input-series-max=500 \
        pe-warn-series-max=500 \
        default-failure-timeout=60s \
        last-lrm-refresh=1597310403 \
        maintenance-mode=false


root@cluster1:~# crm status
Stack: corosync
Current DC: cluster1 (version 2.0.1-9e909a5bdd) - partition with quorum
Last updated: Thu Aug 13 11:23:46 2020
Last change: Thu Aug 13 11:23:00 2020 by root via cibadmin on cluster1

2 nodes configured
6 resources configured (4 DISABLED)

Online: [ cluster1 cluster2 ]

Full list of resources:

 email_alert    (ocf::heartbeat:MailTo):        Started cluster1
 Resource Group: freepbx
     shared_ip_data     (ocf::heartbeat:IPaddr2):       Started cluster1
     srcaddr_ip_data    (ocf::heartbeat:IPsrcaddr):     Started cluster1
     shared_ip_test     (ocf::heartbeat:IPaddr2):       Started cluster1
     srcaddr_ip_test    (ocf::heartbeat:IPsrcaddr):     Stopped (disabled)
     iproute_linkt      (ocf::heartbeat:Route): Stopped (disabled)


root@cluster1:~# crm resource start srcaddr_ip_test

root@cluster1:~# ip r l
default via 192.168.222.1 dev ens18 src **192.168.111.254** onlink 
10.9.0.0/24 via 10.9.0.2 dev tun0 
10.9.0.2 dev tun0 proto kernel scope link src 10.9.0.1 
192.168.111.0/24 dev ens19 scope link src 192.168.111.254 
192.168.222.0/24 dev ens18 scope link src 192.168.222.93

**Comment by Rico29** [comment]
adding "destination" parameter fixes the problem

**Comment by oalbrigt** [comment]
Thank you for your feedback.
