### ISSUE TITLE
"default" route causes errors in /var/log/messages

### ISSUE THREAD

**Issue by ethaniel** [ClusterLabs/resource-agents#1268]
I have the following rule:

```
pcs resource create default_gw ocf:heartbeat:Route destination="default" device="eth0" gateway="89.89.89.89" 
```

I'm getting these errors in the /var/log/messages:
```
Nov 20 02:40:39 haproxy-01 Route(default_gw)[2583953]: ERROR: Address family detection requires a numeric destination address.
Nov 20 02:40:39 haproxy-01 lrmd[643978]:   notice: default_gw_monitor_10000:2583953:stderr [ ocf-exit-reason:Address family detection requires a numeric destination address.
```

According to the source code (https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/Route), the Route resource agent doesn't like 'default' as name of the route, because it can't figure out if it's ipv4 or ipv6:
```
case $OCF_RESKEY_destination in
            *:*)     addr_family="-6" ;;
            *.*)     addr_family="-4" ;;
              *) ocf_exit_reason "Address family detection requires a numeric destination address." ;;
        esac ;;
```

**Comment by ethaniel** [comment]
Quick fix is to use this instead:
```
pcs resource create default_gw ocf:heartbeat:Route destination="0.0.0.0/0" device="eth0" gateway="89.188.102.65" 
```

But this problem needs to be fixed, because according to the manual (https://linux.die.net/man/7/ocf_heartbeat_route) I can use "default" as route name:
```
Specify "0.0.0.0/0" or "default" if you want this resource to set the system default route. (unique, required, string, no default)
```

**Comment by krig** [comment]
As the error message says, you need to specify address family (ip4 or ip6) when using "default". By using "0.0.0.0/0", this implies IPv4.
