### ISSUE TITLE
ocf:heartbeat:Route 4.1.1 is breaking compatibily with existing scripts

### ISSUE THREAD

**Issue by fpicot** [ClusterLabs/resource-agents#1282]
Existing scripts using ocf: heartbeat:Route break under resource-agent 4.1.1, due to the new parameter "family". 
This new parameter was introduced in #1023 comes with a default value "detect", but is set to be mandatory. 
As the default value of "detect" falls back to previous behavior, the parameter should not be mandatory.

**Comment by oalbrigt** [comment]
https://github.com/ClusterLabs/resource-agents/pull/1283
