### ISSUE TITLE
VirtualDomain does not really stop kvm VM using virsh destroy

### ISSUE THREAD

**Issue by slesru** [ClusterLabs/resource-agents#1293]
Hello!

I  just created bug report on redhat https://bugzilla.redhat.com/show_bug.cgi?id=1669032

So I will copy it's content here , with some minor changes:

https://bugzilla.redhat.com/show_bug.cgi?id=1669032

            Bug ID: 1669032
           Summary: VirtualDomain does not really stop kvm VM using virsh
                    destroy
           Product: Red Hat Enterprise Linux 7
           Version: 7.6
          Hardware: x86_64
                OS: Linux
            Status: NEW
         Component: pacemaker
          Severity: medium
          Assignee: kgaillot@redhat.com
          Reporter: dm@belkam.com
        QA Contact: cluster-qe@redhat.com
                CC: abeekhof@redhat.com, cluster-maint@redhat.com
  Target Milestone: rc
    Classification: Red Hat

Description of problem:

We run test 3 node cluster without stonith
no-quorum-policy is set to stop.

When we isolate one node (marduk) pacemaker thinks it stopped VM, but really
not:

[root@marduk ~]# pcs status
Cluster name: cluster
Stack: corosync
Current DC: marduk (version 1.1.19-8.el7_6.1-c3c624ea3d) - partition WITHOUT
quorum
Last updated: Thu Jan 24 11:20:49 2019
Last change: Thu Jan 24 10:47:55 2019 by hacluster via crmd on marduk

3 nodes configured
4 resources configured

Online: [ marduk ]
OFFLINE: [ ashur ishtar ]

Full list of resources:

w8test      (ocf::heartbeat:VirtualDomain):      Stopped

Daemon Status:
 corosync: active/enabled
 pacemaker: active/enabled
 pcsd: active/enabled

at the same time:

[root@marduk ~]# virsh domstate w8test
running

and it can be stopped:

[root@marduk ~]# virsh destroy w8test
Domain w8test destroyed

[root@marduk ~]# virsh domstate w8test
error: failed to get domain 'w8test'
error: Domain not found: no domain with matching name 'w8test'

Domain can't be stopped gracefully, because we also isolate gluster, so there
is no quorum on gluster , so i/o is stopped.

Domain can only be destroyed, and this is where VirtualDomain fails.

Version-Release number of selected component (if applicable):

This is Centos 7.6 with all components from it's repositories.

How reproducible:

Steps to Reproduce:
1. Install 3 nodes cluster without stonith
with no-quorum-policy  stop
2. Create VirtualDomain kvm VM, which can't be gracefully stopped
3. Isolate node using iptables.

Actual results:
VM is running, pacemaker thinks it is stopped

Expected results:

VM is stopped

Additional info:
We also tried to set force_stop
[root@marduk ~]# pcs resource show  w8test
Resource: w8test (class=ocf provider=heartbeat type=VirtualDomain)
 Attributes: config=/kvmpool/qemu_config/w8test.xml hypervisor=qemu:///system
migration_transport=ssh force_stop=1
 Meta Attrs: allow-migrate=true priority=100 
 Utilization: cpu=2 hv_memory=2048
 Operations: migrate_from interval=0 timeout=120s
(w8test-migrate_from-interval-0)
             migrate_to interval=0 timeout=120 (w8test-migrate_to-interval-0)
             monitor interval=240 timeout=120 (w8test-monitor-interval-240)
             start interval=0s timeout=120s (w8test-start-interval-0s)
             stop interval=0s timeout=120s (w8test-stop-interval-0s)

Result is the same, i.e. forcestop does not work.

But, according to log it works:

Jan 24 11:26:54  VirtualDomain(w8test)[3802678]:    INFO: Issuing graceful
shutdown request for domain w8test.
Jan 24 11:28:49  VirtualDomain(w8test)[3802678]:    INFO: Issuing forced
shutdown (destroy) request for domain w8test.

but domain is running..

Looks very strange.
Could you tell me what can be wrong here?

Thank you!

**Comment by slesru** [comment]
Thank you! This works as expected on healthy cluster,

And t executes virsh --connect=qemu:///system --quiet destroy w8test 
looks almost the same as 
virsh destroy w8test , which works from shell.

will try to do this on "broken" asap, I guess next week.

This can be not pacemaker, but virsh problem...

Thank you!

**Comment by oalbrigt** [comment]
It could be a SELinux issue as well.

[SELinux documentation for troubleshooting/temporarily disabling while testing](https://wiki.centos.org/HowTos/SELinux)

**Comment by slesru** [comment]
Hello!

We forgot that we have domain definition files on shared storage, namely the same gluster,
so if only one machine is available, it is impossible to read them, because there is no gluster quorum
Libvirt does not need these files to operate VMs, but VirtualDomain needs them:

>  stderr: + 13:47:01: VirtualDomain_validate_all:973: '[' stop = stop ']'
>  stderr: + 13:47:01: VirtualDomain_validate_all:974: ocf_log info 'Configuration file /kvmpool/qemu_config/w8test.xml not readable, resource considered stopped.'

and, if it can't read domain definition it thinks it is stopped.

Not good, but, I guess, everything works as it should.
It is really will be good if VirtualDomain will have the same behaviour as virsh, but...

Looks like this is not bug. Thank you!

**Comment by oalbrigt** [comment]
Thanks for your feedback. That might be worth considering improving in the future.
