### ISSUE TITLE
nfsserver resource nfsv4

### ISSUE THREAD

**Issue by gss2002** [ClusterLabs/resource-agents#1315]
Is there a known way to follow the Redhat NFSv4 Only steps as it seems like the ResourceAgents nfsserver does not support disabling nfs3/4 components out of the box right now?

Procedure 8.2. Configuring an NFSv4-only Server - https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/configuring_and_managing_high_availability_clusters/assembly_configuring-active-passive-nfs-server-in-a-cluster.adoc-configuring-and-managing-high-availability-clusters

To configure your NFS server to support only NFS version 4.0 and later:
Disable NFSv2, NFSv3, and UDP by adding the following line to the /etc/sysconfig/nfs configuration file:
RPCNFSDARGS="-N 2 -N 3 -U"
Optionally, disable listening for the RPCBIND, MOUNT, and NSM protocol calls, which are not necessary in the NFSv4-only case.
The effects of disabling these options are:
Clients that attempt to mount shares from your server using NFSv2 or NFSv3 become unresponsive.
The NFS server itself is unable to mount NFSv2 and NFSv3 file systems.
To disable these options:
Add the following to the /etc/sysconfig/nfs file:
RPCMOUNTDOPTS="-N 2 -N 3"
Disable related services:
# systemctl mask --now rpc-statd.service rpcbind.service rpcbind.socket
Restart the NFS server:
# systemctl restart nfs
The changes take effect as soon as you start or restart the NFS server.

Apr  5 15:31:21 ha21t51fs pengine[1531]:  notice: Calculated transition 5809, saving inputs in /var/lib/pacemaker/pengine/pe-input-679.bz2
Apr  5 15:31:21 ha21t51fs crmd[1532]:  notice: Initiating monitor operation p_nfsserver_monitor_0 locally on ha21t51fs.tech.hdp.example.com
Apr  5 15:31:21 ha21t51fs nfsserver(p_nfsserver)[17184]: ERROR: rpcbind is not running
Apr  5 15:31:21 ha21t51fs crmd[1532]:  notice: Result of probe operation for p_nfsserver on ha21t51fs.tech.hdp.example.com: 7 (not running)
Apr  5 15:31:21 ha21t51fs crmd[1532]:  notice: Initiating start operation p_nfsserver_start_0 locally on ha21t51fs.tech.hdp.example.com
Apr  5 15:31:22 ha21t51fs nfsserver(p_nfsserver)[17219]: ERROR: rpcbind is not running
Apr  5 15:31:22 ha21t51fs nfsserver(p_nfsserver)[17219]: INFO: Starting NFS server ...
Apr  5 15:31:22 ha21t51fs nfsserver(p_nfsserver)[17219]: INFO: Start: rpcbind i: 1
Apr  5 15:31:23 ha21t51fs nfsserver(p_nfsserver)[17219]: INFO: Start: rpcbind i: 2
Apr  5 15:31:24 ha21t51fs nfsserver(p_nfsserver)[17219]: INFO: Start: rpcbind i: 3
Apr  5 15:31:25 ha21t51fs nfsserver(p_nfsserver)[17219]: INFO: Start: rpcbind i: 4
Apr  5 15:31:26 ha21t51fs nfsserver(p_nfsserver)[17219]: INFO: Start: rpcbind i: 5
Apr  5 15:31:27 ha21t51fs nfsserver(p_nfsserver)[17219]: INFO: Start: rpcbind i: 6
Apr  5 15:31:28 ha21t51fs nfsserver(p_nfsserver)[17219]: INFO: Start: rpcbind i: 7

**Comment by oalbrigt** [comment]
The nfsserver agent currently requires rpcbind and a set of other services, but I guess we could make parameters to disable specific services in the future to be able to run NFSv4 without those services.

**Comment by nrwahl2** [comment]
@oalbrigt Is this resolved by Pull 1498?

**Comment by oalbrigt** [comment]
Correct. This was fixed in #1498.
