### ISSUE TITLE
Bad unit name for systemd

### ISSUE THREAD

**Issue by crequill** [ClusterLabs/resource-agents#1335]
Why are you using TOMCAT_NAME for tomcat unit name. See on line 198: 
`	if ocf_is_true $SYSTEMD; then
             systemctl $@ tomcat@${TOMCAT_NAME}`

On most system it’s only tomcat.

**Comment by oalbrigt** [comment]
To use the specific config the agent generates.

**Comment by crequill** [comment]
On redhat 7 I always get unit not found with force_systemd=1.

**Comment by oalbrigt** [comment]
It is in the tomcat package on RHEL7. Are you using Tomcat from a 3rd party repository?

**Comment by crequill** [comment]
OK sorry it’s from a third repostory.

**Comment by oalbrigt** [comment]
No worries. You might want to report it to them, so others wont get the same issue.
