### ISSUE TITLE
creating customize resource agent

### ISSUE THREAD

**Issue by GQiang88** [ClusterLabs/resource-agents#1348]
[PaceMaker_Syslog-ng.txt](https://github.com/ClusterLabs/resource-agents/files/3259905/PaceMaker_Syslog-ng.txt)

Hi,

I am new to creating customize RA in pacemaker. The following are the steps i done.
1. Create my RA in /usr/lib/ocf/resource.d/heartbeat/syslogng
2. I key in the following command "pcs resource create my_syslogng ocf:heartbeat:syslogng configfile=/opt/syslog-ng/var/run/syslog-ng.ctl"

However  faced with the following error
"Error: Agent 'ocf:heartbeat:syslogng' is not installed or does not provide valid metadata: Metadata query for ocf:heartbeat:syslogng failed: Input/output error, use --force to override"

Please give me some guidance. (I attached my codes)

**Comment by oalbrigt** [comment]
I dont see any apparent issues, so maybe you just forgot to `chmod +x` the file?

You can try running it manually like this:
```
cd /usr/lib/ocf/resource.d/heartbeat
OCF_ROOT=../../ ./syslogng meta-data
```

**Comment by GQiang88** [comment]
Hi oalbrigt,

Thanks for replying to me, i trying running it manually like you suggested.
However i face this error.
-bash: ./syslogng: @BASH_SHELL@: bad interpreter: No such file or directory

The file is executable.
-rwxr-xr-x. 1 root root  6091 Jun  4 17:06 syslogng

**Comment by GQiang88** [comment]
OMG, i know why. Thanks, i will further troubleshoot myself.

**Comment by GQiang88** [comment]
Hi,

[root@syslogng01 heartbeat]# pcs resource show my_syslogng
 Resource: my_syslogng (class=ocf provider=heartbeat type=syslogng)
  Attributes: configfile=/opt/syslog-ng/etc/syslog-ng.conf
  Operations: monitor interval=60s timeout=60s (my_syslogng-monitor-interval-60s)
              start interval=0s timeout=60s (my_syslogng-start-interval-0s)
              stop interval=0s timeout=120s (my_syslogng-stop-interval-0s)

How do i use the configfile value?
Is my following code wrong?

	CONFIGFILE="${OCF_RESKEY_configfile}"
	echo "The value is $OCF_RESKEY_configfile"
	if [[ -z "$CONFIGFILE" ]]; then
		ocf_log err "undefined parameter:configfile"
		exit $OCF_ERR_CONFIGURED
	fi

The echo show no value at all.

**Comment by oalbrigt** [comment]
Use e.g. `ocf_log err` instead of echo.

**Comment by GQiang88** [comment]
I used both previously. There no value in my OCF_RESKEY_configfile.
However, when i key in "pcs resource show my_syslogng" There is configfile attribute.
I do a ocf_log err right before my main code.

[root@syslogng01 heartbeat]# OCF_ROOT=../../ ./syslogng start
ERROR: configfile value =
ERROR: undefined parameter:

There really no configfile value. Is my concept of calling the attributes wrong?
I even went ahead to set default value for configfile.
Still no value.

        <parameters>
        <parameter name="configfile" unique="0" required="1">
        <longdesc lang="en">
        This parameter specifies a configuration file
        for a syslog-ng instance managed by this RA.
        </longdesc>
        <shortdesc lang="en">Configuration file name with full path </shortdesc>
        <content type="string" default="/opt/syslog-ng/etc/syslog-ng.conf"/>
        </parameter>

**Comment by krig** [comment]
When you run the agent yourself from the command line, nothing is setting the environment variables for you - that's why you have to set `OCF_ROOT` manually too, for example. So you have to also set `OCF_RESKEY_...` for all the parameter values to you want to pass in, or any other environment variables that the agent expects to be there.

**Comment by GQiang88** [comment]
Ok! i got it now.
I manually run the agent with the following command.
 OCF_ROOT=../../ OCF_RESKEY_configfile=/opt/syslog-ng/etc/syslog-ng.conf ./syslogng start
