### ISSUE TITLE
PostgreSQL 12

### ISSUE THREAD

**Issue by windowsisnotos** [ClusterLabs/resource-agents#1424]
Good afternoon. Are you planning to add PostgreSQL 12 support? If yes, then when?

**Comment by knakahira** [comment]
Hi, @windowsisnotos 

I'm planning to add PostgreSQL 12 support for pgsql RA.
And I will make a pull request at the beginning of next year.

I think that it is no problem Active/Standby use with shared disk.

But, streaming replication's specification has changed and It is necessary to switch start process according to the PostgreSQL version.

Important change in the PostgreSQL 12 is below:
https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=2dedf4d9a899b36d1a8ed29be5efbd1b31a8fe85

recovery.conf has been integrated into postgresql.conf and standby_mode has been deprecated.
Instead, a standby.signal file must be created when slave starts.

I am considering a new startup method and creating a test code in my test environment(RHEL 8.0 + Pacemaker-2.0.1-4 + PostgreSQL 12) now, but It will take a while.

Please let me know If you have any comments and advice.

**Comment by windowsisnotos** [comment]
Yes, I'm interested in streaming replication. I think that transferring recovery.conf to postgresql.conf is not a big problem, since you can add the necessary parameters through the include option in postgresql.conf. Or am I mistaken?

**Comment by knakahira** [comment]
@windowsisnotos
You are right. I was thinking that creating recovery.conf under "/var/lib/pgsql/tmp/" and including it from postgresql.conf.(like a rep_mode.conf)
And I thought about putting all the parameters in rep_mode.conf, but I stopped it because I didn't want to affect the master operation.

For the rest of the work, add a process to create a standby.signal file instead of standby_mode and the start process switching by PostgreSQL version.
If you have other considerations, please let me know.

**Comment by knakahira** [comment]
Hi, all

I made a alpha version patch for support PostgreSQL 12.
This is still being tested and may change in the future.

Please try it and tell me if you noticed any bugs or lack of functions.

https://github.com/knakahira/resource-agents/commit/a43075be72683e1d4ddab700ec16d667164d359c

**Comment by windowsisnotos** [comment]
Hello. I put together a test bench on which I installed PostgreSQL 12 and conducted several tests. Failover was successful, when can  expect a release with PostgreSQL 12 support?

**Comment by knakahira** [comment]
@windowsisnotos 
I will make a pull request in January.
But, I am not managing the release of the resource-agents and I don't know when it will be merged.

And then, I am examining whether unexpected failures occur.
If you find a failure pattern that does not work well, please let me know.

**Comment by knakahira** [comment]
Hi, all

The alpha version patch was missing consideration for "restart_on_promote=true".
(Tanks for munenari)

https://github.com/knakahira/resource-agents/pull/1

After applying the above patch, the issue appears to be resolved.

If anyone finds the problem, please let me know.

**Comment by LeMerP** [comment]
Hi,

my thanks to @knakahira and @munenari.
Patch works great for us.

Kind regards

**Comment by oalbrigt** [comment]
Thanks for the patch and testing.

**Comment by goldyfruit** [comment]
@LeMerP  @knakahira Could you please share how you created the `pgsql` resource?
We are following https://wiki.clusterlabs.org/wiki/PgSQL_Replicated_Cluster but doesn't seems to be updated.

**Comment by knakahira** [comment]
@goldyfruit I think that resource configuration for the pgsql RA is not changed from PostgreSQL 11 basically.
And the pgsql RA work with Pacemaker 1.1.21 and 2.0.x.
If you have any trouble, please send your configuration and logs to users@clusterlabs.org or make a new issue.
