### ISSUE TITLE
ldirectord: FR ldaps

### ISSUE THREAD

**Issue by goldzahn** [ClusterLabs/resource-agents#1436]
I need ldirectord to handle ldaps as a service so I could use checktype=negotiate for ldaps.
At the moment I have to use checktype=connect which is not sufficient enough in case of certain problems. Unfortunately, I don't have experience in perl, so I can't really create a pull request for that myself. I would really appreciate your help :)

**Comment by vvidic** [comment]
Proposed fix in #1517

**Comment by vvidic** [comment]
ldaps added in 4.6.0.

**Comment by goldzahn** [comment]
I tested the new version and it looks good.
Thanks a lot for your help!
