### ISSUE TITLE
Question: Redis RA: validate_all always fails with ERR_INSTALLED

### ISSUE THREAD

**Issue by zaenk** [ClusterLabs/resource-agents#1446]
## Environment

I started using the redis RA in a cluster with Ubuntu 14.04 hosts and somewhat older pacemaker (1.1.10+git201308) and corosync (2.3.3-1ubuntu4) versions. I had to replace the `  #!@BASH_SHELL@` with `#!/bin/bash` in order to make it work.

## Description of the issue

The `redis_validate` check failed on all nodes with `ERR_INSTALLED`, even the ones where the binaries were present.

In `redis_validate` I replaced the `[[ -x "$REDIS_XXX" ]]` and `[[ -f "$REDIS_CONFIG" ]]` tests with `[[ ! -x "$REDIS_XXX" ]]` and `[[ ! -f "$REDIS_CONFIG" ]]` to make it work.

Related code block below

https://github.com/ClusterLabs/resource-agents/blob/90eddad56e688fca4fca82ab1e51b12e11f9cc78/heartbeat/redis.in#L700-L717

## Question

Are those checks in `redis_validate` working properly for anyone else? And is yes, why?

**Comment by oalbrigt** [comment]
`#!@BASH_SHELL@` is replaced when running `make`, and the rest of your issues are probably caused by your redis files not being located where the agent expects them.

If you run `pcs resource describe redis` you can see the parameter names and change them for your resource for it to work correctly.

**Comment by zaenk** [comment]
I executed following test:

```sh
# download the RA
$ wget https://raw.githubusercontent.com/ClusterLabs/resource-agents/master/heartbeat/redis.in -O /usr/lib/ocf/resource.d/heartbeat/redis.in
$ sha1sum /usr/lib/ocf/resource.d/heartbeat/redis.in
ea882d82e30721167026d0f41c39ed6abac0c80c  /usr/lib/ocf/resource.d/heartbeat/redis.in
$ chmod +x /usr/lib/ocf/resource.d/heartbeat/redis.in
# replace 1st line shabang
$ sed -i "1 s|^.*$|#!/bin/bash|" /usr/lib/ocf/resource.d/heartbeat/redis.in

# validating binaries
$ ls -al /usr/local/bin/redis-server
-rwxr-xr-x 1 root root 8328690 Jan 13 18:25 /usr/local/bin/redis-server
$ ls -al /usr/local/bin/redis-cli
-rwxr-xr-x 1 root root 4948472 Jan 13 18:25 /usr/local/bin/redis-cli
$ ls -al /etc/redis/redis.conf
-rwxr-xr-x 1 redis redis 61874 Jan 14 14:20 /etc/redis/redis.conf

# setting variables for debugging like in https://wiki.clusterlabs.org/wiki/Debugging_Resource_Failures
$ export OCF_ROOT=/usr/lib/ocf
$ export OCF_RESKEY_bin=/usr/local/bin/redis-server
$ export OCF_RESKEY_client_bin=/usr/local/bin/redis-cli

# test
$ /usr/lib/ocf/resource.d/heartbeat/redis.in validate-all
$ /usr/lib/ocf/resource.d/heartbeat/redis.in: line 720: ocf_attribute_target: command not found
DEBUG: action=validate-all notify_type= notify_operation= master_host= slave_host= promote_host= demote_host=; params: bin=/usr/local/bin/redis-server client_bin=/usr/local/bin/redis-cli config=/etc/redis/redis.conf user=redis rundir=/var/run/redis port=6379
ERROR: validate: /usr/local/bin/redis-server does not exist or is not executable
DEBUG: exit_status=5

# or if you just execute the if in from redis_validate
$ if [[ -x "$OCF_RESKEY_bin" ]]; then echo 'error not installed'; fi
error not installed
$ if [[ -x /bin/bash ]]; then echo 'error not installed'; fi
error not installed

# but it should be
$ if [[ ! -x "$OCF_RESKEY_bin" ]]; then echo 'error not installed'; else echo 'ok'; fi
ok
```

So that's why I think a negation is missing.

**Comment by oalbrigt** [comment]
Oh. It seems you might be right.

I guess I misread it, and I also expected it to be run for some of the other operations, which it clearly isnt.
