### ISSUE TITLE
CentOS and IPSrcAddr resource

### ISSUE THREAD

**Issue by MikeRavenelle** [ClusterLabs/resource-agents#1450]
**Platform**
CentOS 7

**Version**
Master

**Issue**
Using IPSrcAddr on CentOS causes errors on node that is it assigned to when releasing the resource.

**Steps to perform**
Enable debug info for logging
Have IpSrcAddr resource on pacemaker cluster.
Restart the node that currently is assigned the resource
Node hangs on restart because resource is not released
After around 15-20 minutes node restarts (multiple attempts to release resource)
Check log

**Errors**
```
Jan 20 15:24:57 centos-n01 IPsrcaddr(virtual_src_ip)[26802]: ERROR: command 'ip route replace  172.19.0.0/24 dev eno1 proto kernel scope host src ' failed
Jan 20 15:24:57 centos-n01 lrmd[2143]:  notice: virtual_src_ip_stop_0:26802:stderr [ Device "eth0" does not exist. ]
Jan 20 15:24:57 centos-n01 lrmd[2143]:  notice: virtual_src_ip_stop_0:26802:stderr [ Command line is not complete. Try option "help" ]
Jan 20 15:24:57 centos-n01 lrmd[2143]:  notice: virtual_src_ip_stop_0:26802:stderr [ ocf-exit-reason:command 'ip route replace  172.19.0.0/24 dev eno1 proto kernel scope host src ' failed ]
Jan 20 15:24:57 centos-n01 crmd[2146]:  notice: Result of stop operation for virtual_src_ip on centos-n01: 1 (unknown error)
Jan 20 15:24:57 centos-n01 crmd[2146]:  notice: centos-n01-virtual_src_ip_stop_0:63 [ Device "eth0" does not exist.\nCommand line is not complete. Try option "help"\nocf-exit-reason:command 'ip route replace  172.19.0.0/24 dev eno1 proto kernel scope host src ' failed\n ]
Jan 20 15:24:57 centos-n01 crmd[2146]: warning: Action 30 (virtual_src_ip_stop_0) on centos-n01 failed (target: 0 vs. rc: 1): Error
Jan 20 15:24:57 centos-n01 crmd[2146]:  notice: Transition aborted by operation virtual_src_ip_stop_0 'modify' on centos-n01: Event failed
```

**Comment by MikeRavenelle** [comment]
So the issue seems to stem from the fact that the src option does not have a value.

`	OPTS=""
	if [ "$OCF_RESKEY_destination" != "0.0.0.0/0" ] ;then
		PRIMARY_IP="$($IP2UTIL -4 -o addr show dev $INTERFACE primary | awk '{split($4,a,"/");print a[1]}')"
		OPTS="proto kernel scope host src $PRIMARY_IP"
	fi

	$IP2UTIL route replace $TABLE $NETWORK dev $INTERFACE $OPTS || \
		errorexit "command 'ip route replace $TABLE $NETWORK dev $INTERFACE $OPTS' failed"`

When I manually run the command to set the PRIMARY_IP.

`ip -4 -o addr show dev eno1 primary | awk '{split($4,a,"/");print a[1]}'`

It displays the correct IP address for the adapter.

**Comment by oalbrigt** [comment]
Seems like you might need to add our latest patch to it (I accidentally hardcoded eth0 for primary IP, which it says "does not exist" in your log).

**Comment by oalbrigt** [comment]
https://github.com/ClusterLabs/resource-agents/pull/1447

**Comment by MikeRavenelle** [comment]
I know get this error when rebooting.

```
Jan 21 11:38:01 centos-n01 IPsrcaddr(virtual_src_ip)[20124]: ERROR: command 'ip route replace  172.19.0.0/24 dev eno1 proto kernel scope host src 172.19.10.166#012172.19.10.168' failed
Jan 21 11:38:01 centos-n01 lrmd[6338]:  notice: virtual_src_ip_stop_0:20124:stderr [ Error: either "to" is duplicate, or "172.19.10.168" is a garbage. ]
Jan 21 11:38:01 centos-n01 lrmd[6338]:  notice: virtual_src_ip_stop_0:20124:stderr [ ocf-exit-reason:command 'ip route replace  172.19.0.0/24 dev eno1 proto kernel scope host src 172.19.10.166 ]
Jan 21 11:38:01 centos-n01 lrmd[6338]:  notice: virtual_src_ip_stop_0:20124:stderr [ 172.19.10.168' failed ]
Jan 21 11:38:01 centos-n01 crmd[6341]:  notice: Result of stop operation for virtual_src_ip on centos-n01: 1 (unknown error)
Jan 21 11:38:01 centos-n01 crmd[6341]:  notice: centos-n01-virtual_src_ip_stop_0:67 [ Error: either "to" is duplicate, or "172.19.10.168" is a garbage.\nocf-exit-reason:command 'ip route replace  172.19.0.0/24 dev eno1
 proto kernel scope host src 172.19.10.166\n172.19.10.168' failed\n ]
Jan 21 11:38:01 centos-n01 crmd[6341]: warning: Action 26 (virtual_src_ip_stop_0) on centos-n01 failed (target: 0 vs. rc: 1): Error
Jan 21 11:38:01 centos-n01 crmd[6341]:  notice: Transition aborted by operation virtual_src_ip_stop_0 'modify' on centos-n01: Event failed
```

**Comment by oalbrigt** [comment]
Somehow it's returning 2 lines for primary in your case.

You can try changing the awk-part to awk `NR==1'{split($4,a,"/");print a[1]}'` to only catch the first line.

**Comment by MikeRavenelle** [comment]
Awesome that did it!

There are still a few issues I am having with regards to CentOS so I will leave this open for now. Currently the resource is running and shuts down correctly but packets are not being sourced from the configured IP address. I will add a comment once I have more data.

Are there inherent difference between how these operations work on CentOS than Ubuntu? My previous cluster configuration was on Ubuntu and IPsrcaddr works flawlessly without any issues.

**Comment by oalbrigt** [comment]
You probably werent able to set destination on your previous setup (pretty new feature, which just allows to specify that it only gets set for specific IP/subnet).

**Comment by MikeRavenelle** [comment]
This is the command I used on both my Ubuntu install as well as this new CentOS install. The requirement for setting a destination was actually needed on Ubuntu.

`sudo pcs resource create virtual_src_ip IPsrcaddr ipaddress="172.19.10.168" cidr_netmask="24" destination="172.19.0.0/24" op monitor interval="1s" timeout="20s" meta migration-threshold="2" failure-timeout="20s"`

**Comment by MikeRavenelle** [comment]
So far the syslogs do not show any errors when the resource is started. 

I am testing with the ping command to check if outgoing packets are being correctly sourced. Ubuntu is working, CentOS is not. Side note, multicast traffic is also not being sourced correctly but that is consistent between both Ubuntu and CentOS.

I am not sure what more information I can provide but my ifconfig and routing table are below. These look the same between Ubuntu and CentOS  (besides different physical IP addresses and adapter names).

```
ifconfig
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.19.10.166  netmask 255.255.0.0  broadcast 172.19.255.255
        inet6 fe80::8c8f:80d9:4745:ddd9  prefixlen 64  scopeid 0x20<link>
        ether 00:30:18:c2:dc:76  txqueuelen 1000  (Ethernet)
        RX packets 164781  bytes 20162795 (19.2 MiB)
        RX errors 0  dropped 189  overruns 0  frame 0
        TX packets 69999  bytes 9918951 (9.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf7d00000-f7d20000

enp2s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 00:30:18:c2:dc:77  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 18  memory 0xf7c00000-f7c20000

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 12046  bytes 1801889 (1.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 12046  bytes 1801889 (1.7 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

```
route -n
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.19.100.168  0.0.0.0         UG    100    0        0 eno1
172.19.0.0      0.0.0.0         255.255.255.0   U     0      0        0 eno1
172.19.0.0      0.0.0.0         255.255.0.0     U     100    0        0 eno1
172.19.10.0     0.0.0.0         255.255.255.0   U     0      0        0 eno1
```

**Comment by oalbrigt** [comment]
Output from `ip a` and `ip r` would be more informative, and also and example of which IP you're connecting to where it doesnt work. Maybe you should try using table=local, and see if that helps?

**Comment by MikeRavenelle** [comment]
ip a
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eno2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether ac:1f:6b:80:cf:59 brd ff:ff:ff:ff:ff:ff
3: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether ac:1f:6b:80:cf:58 brd ff:ff:ff:ff:ff:ff
    inet 172.19.10.167/16 brd 172.19.255.255 scope global noprefixroute eno1
       valid_lft forever preferred_lft forever
    inet 172.19.10.168/24 brd 172.19.255.255 scope global eno1
       valid_lft forever preferred_lft forever
    inet6 fe80::6731:6b84:5630:710c/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
```

ip r
```
default via 172.19.100.168 dev eno1 proto static metric 101
172.19.0.0/24 dev eno1 scope link src 172.19.10.168
172.19.0.0/16 dev eno1 proto kernel scope link src 172.19.10.167 metric 101
172.19.10.0/24 dev eno1 proto kernel scope link src 172.19.10.168
```

I am pining the address 172.19.100.39 and capturing in wireshark. As stated before it does not show the source ip correctly. When this same test is done on the ubuntu cluster it does show correctly.

I will go ahead and try adding the option table=local to the resource and see if that helps.

**Comment by oalbrigt** [comment]
172.19.100.39 is not part of the 172.19.0.0/24 range (172.19.0.x).

**Comment by MikeRavenelle** [comment]
Duh! That of course fixed it. Thanks for you continued support. 

One last question before I close the issue.

The fix from earlier changing the script to:

`NR==1'{split($4,a,"/");print a[1]}`

Is this something that will be changed in the repo or will I have to do this for every deployment?

**Comment by oalbrigt** [comment]
What output do you get when you run `ip -4 -o addr show dev eno1 primary`? I dont get why it returns 2 primary IPs in your case.

**Comment by MikeRavenelle** [comment]
ip -4 -o addr show dev eno1 primary :
`2: eno1    inet 172.19.10.166/16 brd 172.19.255.255 scope global noprefixroute eno1\       valid_lft forever preferred_lft forever`

**Comment by oalbrigt** [comment]
Strange. Can you do some further testing without NR==1, and see if it's working fine in started/stopped state etc now?

**Comment by oalbrigt** [comment]
And if it fails on e.g. stop run that command to get the output when it's failing.

**Comment by MikeRavenelle** [comment]
Removing NR==1 resulted in failure.

Error:
```
Jan 31 11:31:45 centos-n01 IPsrcaddr(virtual_src_ip)[12163]: ERROR: command 'ip route replace  172.19.0.0/16 dev eno1 proto kernel scope host src 172.19.10.166#012172.19.10.168' failed
Jan 31 11:31:45 centos-n01 lrmd[1816]:  notice: virtual_src_ip_stop_0:12163:stderr [ Error: either "to" is duplicate, or "172.19.10.168" is a garbage. ]
Jan 31 11:31:45 centos-n01 lrmd[1816]:  notice: virtual_src_ip_stop_0:12163:stderr [ ocf-exit-reason:command 'ip route replace  172.19.0.0/16 dev eno1 proto kernel scope host src 172.19.10.166 ]
Jan 31 11:31:45 centos-n01 lrmd[1816]:  notice: virtual_src_ip_stop_0:12163:stderr [ 172.19.10.168' failed ]
Jan 31 11:31:45 centos-n01 crmd[1819]:  notice: Result of stop operation for virtual_src_ip on centos-n01: 1 (unknown error)
Jan 31 11:31:45 centos-n01 crmd[1819]:  notice: centos-n01-virtual_src_ip_stop_0:63 [ Error: either "to" is duplicate, or "172.19.10.168" is a garbage.\nocf-exit-reason:command 'ip route replace  172.19.0.0/16 dev eno1 proto kernel scope host src 172.19.10.166\n172.19.10.168' failed\n ]
Jan 31 11:31:45 centos-n01 crmd[1819]: warning: Action 16 (virtual_src_ip_stop_0) on centos-n01 failed (target: 0 vs. rc: 1): Error
Jan 31 11:31:45 centos-n01 crmd[1819]:  notice: Transition aborted by operation virtual_src_ip_stop_0 'modify' on centos-n01: Event failed
```
ip -4 -o addr show dev eno1 primary :
```
2: eno1    inet 172.19.10.166/16 brd 172.19.255.255 scope global noprefixroute eno1\       valid_lft forever preferred_lft forever
2: eno1    inet 172.19.10.168/24 brd 172.19.255.255 scope global eno1\       valid_lft forever preferred_lft forever
```

**Comment by oalbrigt** [comment]
Ah. The IP is considered primary if you dont set `table=local` for the resource.

**Comment by MikeRavenelle** [comment]
I will go ahead and try that and report back!

**Comment by nrwahl2** [comment]
Any luck @MikeRavenelle ?

**Comment by MikeRavenelle** [comment]
I am still using the modification 

> NR==1'{split($4,a,"/");print a[1]}

I have not gotten a chance to try

>  table=local

**Comment by nrwahl2** [comment]
Understood. I believe you'll also need to specify the `destination` attribute in addition to `table=local`.

**Comment by oalbrigt** [comment]
Closing. Reopen if this is still an issue.
