### ISSUE TITLE
awsvip fails to start on creation in Ubuntu 16.04

### ISSUE THREAD

**Issue by rangacherukuri** [ClusterLabs/resource-agents#1466]
I created a three node cluster using pacemaker and Ubuntu 16.04 on aws.

for virtual ip i used awsvip agent and below is the command I used to create resource.

sudo pcs resource create p_awsvip5 ocf:heartbeat:awsvip awscli="/usr/bin/aws" secondary_private_ip=172.31.34.20 op monitor timeout="30s" interval="20s"

creation is successful, but the pcs status show it is stopped state. the action log does not help much.

sudo pcs status
Cluster name: ag1
Last updated: Tue Mar 24 08:11:03 2020		Last change: Tue Mar 24 08:10:47 2020 by root via cibadmin on NODE3
Stack: corosync
Current DC: NODE2 (version 1.1.14-70404b0) - partition with quorum
3 nodes and 4 resources configured

Online: [ NODE2 NODE3 ]
OFFLINE: [ NODE1 ]

Full list of resources:

 Master/Slave Set: ag_cluster-master [ag_cluster]
     Masters: [ NODE3 ]
     Slaves: [ NODE2 ]
     Stopped: [ NODE1 ]
 p_awsvip5	(ocf::heartbeat:awsvip):	Stopped

Failed Actions:
* p_awsvip5_start_0 on NODE3 'not running' (7): call=38, status=complete, exitreason='none',
    last-rc-change='Tue Mar 24 08:10:52 2020', queued=0ms, exec=3681ms
* p_awsvip5_start_0 on NODE2 'not running' (7): call=42, status=complete, exitreason='none',
    last-rc-change='Tue Mar 24 08:10:47 2020', queued=0ms, exec=3673ms

PCSD Status:
  NODE1: Offline
  NODE2: Online
  NODE3: Online

Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled

**Comment by oalbrigt** [comment]
Try running it with `pcs resource debug-start --full p_awsvip5`.

That should give you some info on where it fails.

**Comment by rangacherukuri** [comment]
> Try running it with `pcs resource debug-start --full p_awsvip5`.
> 
> That should give you some info on where it fails.

it starts successfully when I start it manually and the pcs status still shows resource in stopped ststae.

Also, when I created the resource it fails without starting

**Comment by oalbrigt** [comment]
If it starts manually you might have to do `pcs resource cleanup p_awsvip5`. There's also debug-monitor and debug-stop to test why the other actions might fail.

**Comment by rangacherukuri** [comment]
> If it starts manually you might have to do `pcs resource cleanup p_awsvip5`. There's also debug-monitor and debug-stop to test why the other actions might fail.

I used pcs resource cleanup p_awsvip5 
it tried to start resource automatically but still same error.

**Comment by rangacherukuri** [comment]
> If it starts manually you might have to do `pcs resource cleanup p_awsvip5`. There's also debug-monitor and debug-stop to test why the other actions might fail.

Why does it fail only automatic startup ?

**Comment by oalbrigt** [comment]
Try checking /var/log/pacemaker.log and corosync.log.

If you dont find any information there you might need to change the debug setting in /etc/default/pacemaker and restart Pacemaker to increase the amount of logging.

**Comment by rangacherukuri** [comment]
> Try checking /var/log/pacemaker.log and corosync.log.
> 
> If you dont find any information there you might need to change the debug setting in /etc/default/pacemaker and restart Pacemaker to increase the amount of logging.

I found this in corosync.log

notice: operation_finished:	p_awsvip_monitor_0:22549:stderr [  ]
Mar 24 13:03:43 [1354] NODE3       lrmd:   notice: operation_finished:	p_awsvip_monitor_0:22549:stderr [ The config profile (default) could not be found ]
Mar 24 13:03:43 [1352] NODE3        cib:     info: cib_process_request:	Forwarding cib_modify operation for section status to master (origin=local/crmd/60)
Mar 24 13:03:43 [1357] NODE3       crmd:   notice: process_lrm_event:	Operation p_awsvip_monitor_0: not running (node=NODE3, call=64, rc=7, cib-update=60, confirmed=true)
Mar 24 13:03:43 [1357] NODE3       crmd:   notice: process_lrm_event:	NODE3-p_awsvip_monitor_0:64 [ \nThe config profile (default) could not be found\n ]

but I configured the default profile 
<img width="258" alt="Screenshot 2020-03-24 at 6 50 36 PM" src="https://user-images.githubusercontent.com/62590992/77430013-8514a700-6e00-11ea-8f6a-d5ffdc7668bf.png">

**Comment by oalbrigt** [comment]
You need to copy it to the home-directory of the user pacemaker is running under, and to all nodes.

**Comment by rangacherukuri** [comment]
> You need to copy it to the home-directory of the user pacemaker is running under, and to all nodes.

Thanks a lot! it worked
