### ISSUE TITLE
galera  RA example not work in pcs 0.10.1

### ISSUE THREAD

**Issue by GSergeevich** [ClusterLabs/resource-agents#1482]
Example:
Create a galera cluster using nodes rhel7-node1 rhel7-node2 rhel7-node3 :

```
 pcs resource create db galera enable_creation=true \
 wsrep_cluster_address="gcomm://rhel7-auto1,rhel7-auto2,rhel7-auto3" meta master-max=3 --master
```

return:

`Specified options '--master' are not supported in this command pacemaker`

**Comment by oalbrigt** [comment]
https://github.com/ClusterLabs/resource-agents/pull/1565 should solve this.
