### ISSUE TITLE
SAPInstance to allow surpressing start sapstartsrv for special cluster setups

### ISSUE THREAD

**Issue by fmherschel** [ClusterLabs/resource-agents#1542]
For a very special file system setup we need SAPInstnace *not* to start sapstartsrv during probes - at least not permanently.
In the special file system setup the cluster will not switch over the file system which "holds" the SAP instance. Instead the file system is mounted permanently on all cluster nodes. As SAPInstance controls sapstartsrv since many years we need to be carefully not breaking already existing clusters. That fore I suggest to introduce a new swich (aka resource parameter) which
changes from the standard behavior to the new one.
I will provide a suggestion for the switch name and a patch proposal later (via PR).

**Comment by fdanapfel** [comment]
@fmherschel Could you share some more information on what the exact issue is that you are trying to resolve? I. e. why is it necessary that the sapstartsrv process for a SAP instance doesn't get started by the SAPInstance resource agent during probes?

Because as far as I can see by looking at the code of the SAPInstance resource agent the check_sapstartsrv() function checks if the sapstartsrv process is already running, and if it is it should not actually attempt to start it again.

**Comment by fmherschel** [comment]
The reason is that the probe must more carefully report IF a SAPInstance is already running. Again this is for a special
set-up with a paralell mounted FS on all cluster nodes. Here the FS does not any more hinder the SAP instance to be started.
Lets assume that the SAP instance is running before the cluster is started. With takeover-FS it is impossible that the SAP instance is running where the FS is not mounted. But with a constantly dual-mounted FS this could get critical.

**Comment by fdanapfel** [comment]
@fmherschel Thanks for the additional explanation. This is now starting to make sense to me.

So the actual goal here is to prevent the SAPInstance RA from starting a SAP Instance again on a system in case the same SAP Instance was already started outside of the cluster. Correct?

**Comment by fmherschel** [comment]
@fdanapfel 
Its a bit more fuzzy. SAPInstance should not restart sapstartsrv during a probe (beside for a short test only), if the SAPInstance is currently not running.But it needs to report back to the cluster, if  a SAPInstnace resource is already running. This could happen either when starting the cluster when an SAP instance has alraedy been started (on any node). Or it also happens, when you make a resource cleanup, where also all nodes needs to run a SAPInstance probe action. In this latter case the probe needs to guarantee that the SAPInstance resource is not runnign twice. To guarantee this the RA might need (for a short time) to start sapstartsrv (to run GetProcessList). Then it need to stop sapstartsrv on the side where no SAP instance has been detected. 
This gives us the chance to build clusters with just one single NFS mount-point like /usr/sap/<SID>.

**Comment by fmherschel** [comment]
@fdanapfel If you like I could also invite you to a Teams session, so we could speak about that or just having a plain telephone call. I am still not sure, if I managed to explain the problem quite well.

**Comment by fdanapfel** [comment]
@fmherschel Thanks for taking the time to provide more details on this issue 👍 

With your latest explanation this now makes perfect sense to me. So there is no need for a call from my point of view.

The reason I've asked for these details btw. is that I'm prepared in case I'm being asked to review the PR you said you were going to submit for this :)

**Comment by fmherschel** [comment]
@fdanapfel Thanks for asking and having a look onto that. For the complete solution we also need (unfortunately) an additional resource agent which replaces the FS behaviour. The point once we takeover the group we switch ab IP address a FS and an SAP intance.
Once the group is been stopped the SAPInstance RA stopps the SAP instance but keeps sapstartsrv running (which is correct to allow "simple" stops/starts via sapcontrol-clients). In the fS case now the unmount-procedure kills all processes still running so now the sapstartsrv is been stopped.and once the froup is started on the other side only one sapstartsrv is running.
I named the new candidate sapstartsrv and did a first proposal under:
https://github.com/fmherschel/SAPStartSrv-resourceAgent

This ressource agent might also be moved to the clusterlabs project, if you like me to that I do that PR first,
SAPStartSrv "replaces" the FS in the single-mount-point solution. And helps to guarantee that only one sapstartsrv is running.

**Comment by fdanapfel** [comment]
@fmherschel Great to see all the work you've been doing on this and making it available for others as well. But I'm not sure if it makes sense to move this resource agent to the clusterlabs project or not, considering that it currently seems to be just for one specific customer.

Part of the reason for that is that we're still in the process of convincing customers that moving to the new architecture with 'standalone' resources for managing the (A)SCS/ERS instances is the better choice, one reason being that they can use a single filesystem for each instance directory which gets moved around by the cluster depending on where the instance needs to run which avoids some of the issues you are currently trying to solve with this new approach, and if customers are then seeing upstream that they could still use a single filesystem as they did before with the 'master/slave' approach it could make this process more difficult.

**Comment by fmherschel** [comment]
@fdanapfel Yes we are in sync here. The solutions is only for a very specific customer situation. We should make sure/clear in the patch, that this is *not* to be used as a new standard solution.

**Comment by oalbrigt** [comment]
https://github.com/ClusterLabs/resource-agents/pull/1564
