### ISSUE TITLE
[Question] About the correction of PR1555.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/resource-agents#1560]
Hi All,

The following fixes have been made to Filesystem RA.
 - https://github.com/ClusterLabs/resource-agents/pull/1555

We can't see RHBZ # 1843577, so we don't know the details of the problem.

Is the intention of the correction as follows?
1) For users, it is better for a timeout to occur than for fast_stop = true to interrupt the stop prematurely.
2) The reason for supporting RHEL9 or later is that it does not cause confusion to the user as a mere turning point of change.

 * In fact, our users prefer fast_stop = true because Filesystem RA prefers faster stop failures.
 * This is because, in the case of the STONITH model, the earlier the stop failure, the faster the STONITH will execute and the faster the service will fail over.

Best Regards,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
1. Correct. GFS2 is likely to take more than the fast-stop timeout to unmount.
2. Correct. It is to avoid introducing it in the middle of RHEL8.

**Comment by HideoYamauchi** [comment]
Hi oalbrigt ,

> 1. Correct. GFS2 is likely to take more than the fast-stop timeout to unmount.
> 2. Correct. It is to avoid introducing it in the middle of RHEL8.

Thanks for your comment.

Your answer has shown that our perception is correct.
Our users will be using it with the fast_stop parameter set when RHEL9 comes out in the future.

Many thanks,
Hideo Yamauchi.
