### ISSUE TITLE
ocf.py function id_probe() fails on unset env variable

### ISSUE THREAD

**Issue by fmherschel** [ClusterLabs/resource-agents#1579]
In my LAB I have seen that pacemaker does not set the environemnt variable OCF_RESKEY_CRM_meta_interval=0, if a probe is running. While the shell bindings seams to ignore that, the python bindings fails and returns "False" which invokes the RA to tun a normal monitor.

**Comment by fmherschel** [comment]
Try to fit it with PR #1580

**Comment by oalbrigt** [comment]
Thanks. I've merged the PR.
