### ISSUE TITLE
ocf:heartbeat:iface-vlan does not allow multiple vlans by interface (nor multiple VLANs)

### ISSUE THREAD

**Issue by olifre** [ClusterLabs/resource-agents#1581]
Trying:
```
pcs resource create vlan_83 ocf:heartbeat:iface-vlan vlan_interface=bond_in vlan_id=83 vlan_name=bond_in.83 vlan_loose_binding=true --group fw
pcs resource create vlan_84 ocf:heartbeat:iface-vlan vlan_interface=bond_in vlan_id=84 vlan_name=bond_in.84 vlan_loose_binding=true --group fw
```
yields:
```
Error: Value 'bond_in' of option 'vlan_interface' is not unique across 'ocf:heartbeat:iface-vlan' resources. Following resources are configured with the same value of the instance attribute: 'vlan_85', use --force to override
```
However, this seems to be a common usecase, since `vlan_name` will naturally sitll be unique, i.e. the following VLAN interfaces could be created:

- `bond_in.83@bond_in`
- `bond_in.84@bond_in`

It also seems the `vlan_id` field is marked unique. Is this on purpose, and / or am I misusing the resource agent, or is this a bug?

**Comment by oalbrigt** [comment]
Seems like that's not intended, so feel free to make a PR to change these parameters to  unique=0 for the parameters.

**Comment by olifre** [comment]
Thanks for confirming!
I tested it now in our setup, and it seems setting `unique` to `0` indeed appears to make things work as expected. Will prepare a PR later.
