### ISSUE TITLE
awsvip irrelevant stderr logs

### ISSUE THREAD

**Issue by SpitchAG** [ClusterLabs/resource-agents#1624]
awsvip ocf agent outputs network usage logs at each monitoring steps when trying to set the TOKEN variable
TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")

curl -sX fixes the issue

**Comment by oalbrigt** [comment]
Thanks for the heads up. Seems like I'll need to do that for most of the AWS agents.
