### ISSUE TITLE
[Question] About confirmation of "resource-agents-deps.target" at the start of LVM-activate resource.

### ISSUE THREAD

**Issue by HideoYamauchi** [ClusterLabs/resource-agents#1647]
Hi All,

The LVM-activate resource makes the decision to create 99-LVM-activate.conf at start.
But isn't it correct to perform this check with "resource-agents-deps.target" instead of "resource-agents-deps.target.d"?

```
(snip)
lvm_start() {
        if systemd_is_running ; then
        	# Create drop-in to deactivate VG before stopping
		# storage services during shutdown/reboot.
		after=$(systemctl show resource-agents-deps.target.d \
			--property=After | cut -d'=' -f2)

		case "$after" in
			*" blk-availability.service "*)
				;;
			*)
				systemd_drop_in "99-LVM-activate" "After" \
					"blk-availability.service"
				;;
		esac
(snip)
```

After actually generating 99-LVM-activate.conf, the result is as follows.

If you specify "resource-agents-deps.target.d", blk-availability.service is not checked.

```
# systemctl show resource-agents-deps.target.d --property=After | cut -d'=' -f2


```

If you specify "resource-agents-deps.target", blk-availability.service is checked.
```
# systemctl show resource-agents-deps.target --property=After | cut -d'=' -f2
blk-availability.service
```

Best Regards,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
Nice catch. I'll do some testing next week and make a patch.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

Okay!
I will wait for your fix.

Many thanks,
Hideo Yamauchi.

**Comment by oalbrigt** [comment]
You are correct, so I'll make a patch to fix this.

Thank you for reporting it.

**Comment by HideoYamauchi** [comment]
Hi Oyvind,

All right!

Many thanks,
Hideo Yamauchi.

**Comment by nrwahl2** [comment]
Thanks @HideoYamauchi. My original patch with the typos ended up causing a really weird issue with `nfsserver` resources. I'm not sure how. But the fix proposed here resolves it.
  - https://bugzilla.redhat.com/show_bug.cgi?id=1972035

**Comment by HideoYamauchi** [comment]
Hi Reid,

> Thanks @HideoYamauchi. My original patch with the typos ended up causing a really weird issue with `nfsserver` resources. I'm not sure how. But the fix proposed here resolves it.
> 
> * https://bugzilla.redhat.com/show_bug.cgi?id=1972035

Okay!
Thank you for your information.

Many Thnaks.
Hideo Yamauchi.
