### ISSUE TITLE
SAPInstance fails to detect systemd integration

### ISSUE THREAD

**Issue by fmherschel** [ClusterLabs/resource-agents#1680]
SAPInstance does start sapstartsrv directly by starting the process, even if the service is directly integrated into systemd using unit files.

**Comment by oalbrigt** [comment]
Here's an example of how to detect systemd (and services in it) in the agent:
https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/nfsserver#L236-L256

**Comment by fmherschel** [comment]
We can close this issue as commit 5ad5025 and 9a85152 are solving this problem.
