### ISSUE TITLE
Orphaned routes causing connectivity issues

### ISSUE THREAD

**Issue by ttsvetanov359** [ClusterLabs/resource-agents#1692]
Team--

I recently came across an issues with some of the RHEL releases where the routes are not getting removed after the IPaddr2 resource removed the virtual IP address. As there was no official statement yet, the current workaround is to find and remove the route in the function [delete_interface](https://github.com/ClusterLabs/resource-agents/blob/8dc8b40b69d522400e72c883e60e90ddb6392680/heartbeat/IPaddr2#L613) upon stop operation.
This is the snippet I used for fixing the problem:
```
...
ocf_run $CMD || return $OCF_ERR_GENERIC

# Remove the routes, if any
local has_route
has_route=`$IP2UTIL route show table main | grep "^${OCF_RESKEY_ip} dev ${iface}"`
if [ -n "${has_route}" ] ; then
  ocf_log info "Removing the route ($has_route)"
  delete_route "$ipaddr" "$iface" || return $OCF_ERR_GENERIC
fi
...
```

Does that make sense?

Best regards,
Tsvet

**Comment by oalbrigt** [comment]
Which versions of the package has this issue?

**Comment by ttsvetanov359** [comment]
It seems like 2.0.2 according to RHEL package info:
```
pacemaker 2.0.2-3.el8_1.2 - Red Hat x86_64
pacemaker-cli 2.0.2-3.el8_1.2 - Red Hat x86_64
pacemaker-cluster-libs 2.0.2-3.el8_1.2 - Red Hat x86_64
pacemaker-libs 2.0.2-3.el8_1.2 - Red Hat x86_64
pacemaker-schemas 2.0.2-3.el8_1.2 - Red Hat noarch
```

**Comment by oalbrigt** [comment]
You can find it by running `rpm -q resource-agents`.

**Comment by ttsvetanov359** [comment]
This is the details I found in the sos report package-data:
```
resource-agents-4.1.1-33.el8_1.10.x86_64	Wed Jun 23 14:05:47 2021	1624457147	Red Hat, Inc.
```

**Comment by ttsvetanov359** [comment]
I'll need to reopen this case. The issue is not related to the Google's guest agent like we suspected. The guest agent adds local routes with `proto 66` while the routes that caused the connectivity problem were added by the NetworkManager. As the issue does not occur in RHEL 8.2 and higher, the code for removing that route in the function `delete_interface` would be required as a precaution.

**Comment by ttsvetanov359** [comment]
@nrwahl2 -- would you mind reopening this bug? related RH support case 03073802

**Comment by nrwahl2** [comment]
@oalbrigt Is it possible for you to reopen this? I don't have the necessary privilege.

Posted in the current support case:

> I skimmed over the recent comments in this case today, and I apologize if I've missed anything. However, it seems we're in basically the same position as in case 02989908. The suspected cause within Google's scripts was determined not to be the cause. Google is proposing a change to the IPaddr2 resource agent to delete a particular route upon stop.
> 
> 
> My main concern is this: the IPaddr2 resource agent shouldn't delete something that it didn't create in the first place.
> 
> As I believe we discussed in case 02989908, and as it appears Curtis also discussed in this case, the IPaddr2 (which calls `ip addr add`) doesn't invoke NetworkManager to create the problematic route. Additionally, I didn't see anything else in the cluster configuration in case 02989908 that would have created the route. And it's not something that pacemaker or any other component of the cluster stack might do automatically.
> 
> 
> My secondary concern (which seems to be shared by Curtis) is this: the proposed change to the IPaddr2 resource agent would use iproute to delete a route that was created by NetworkManager.
> 
> 
> We can discuss further and consider such a change. I've asked Oyvind to reopen GitHub issue #1692, since I lack the privilege. However, even though the workaround looks straightforward, I have reservations about (a) having IPaddr2 delete something it didn't create and (b) mixing tools/managers. The change seems brittle in light of both of these factors, with the potential to cause now-unforeseen issues in the future.

**Comment by ttsvetanov359** [comment]
It was found that the issue was related to RHEL8.1 and earlier. In RHEL8.2 NM no longer adds the route for the VIP.  The issue is fixed in NetworkManager by [this commit](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/commit/487b5df7169895cf132997b0bc7f402479043066) which is in NetworkManager-1.22.8

**Comment by oalbrigt** [comment]
Thank you for your feedback.
