### ISSUE TITLE
resource-agents/heartbeat/db2

### ISSUE THREAD

**Issue by Delta-One-Two** [ClusterLabs/resource-agents#1717]
RHEL 7.9

[root@rh7dev01 configs]# crm_attribute -$
Pacemaker 1.1.23-1.el7_9.1
Written by Andrew Beekhof

Error seen:
master_fal='Error performing operation: No such device or address'

Line 277
crm_attribute -t nodes -l reboot --node=$node -n $attr -v "$3"

Line 285
 crm_attribute -t nodes -l reboot -n $attr -G --quiet 2>&1

If I try from the command line I see the same error:

[root@rh7dev01 configs]# crm_attribute -t nodes -l reboot -n db2hadr_db2cce_CCE_fal -G --quiet
Error performing operation: No such device or address

If I swap -t and -l it works:

[root@rh7dev01 configs]# crm_attribute -l reboot -t nodes -n db2hadr_db2cce_CCE_fal -G --quiet
S0000000099.LOG

If I omit -l reboot (which I believe is the default, though I am obviously not going to assume that will always be the case), it works:

[root@rh7dev01 configs]# crm_attribute -t nodes -n db2hadr_db2cce_CCE_fal -G --quiet
S0000000099.LOG

If I change it in the code (swapping -t and -l), the error no longer appears.

**Comment by oalbrigt** [comment]
-t nodes and -l reboot conflicts with eachother, so I'll make a patch to remove -t nodes.

**Comment by Delta-One-Two** [comment]
You can just swap the order and it will work. Removing "-t nodes" will also cause a failure.

[root@rh7dev01 configs]# crm_attribute -l reboot -n db2hadr_db2cce_CCE_fal -G --quiet
Error performing operation: No such device or address

If anything, if you want to rely on the defaults then remove "-l reboot" as this is the default. So to confirm:

**# FAILING QUERIES**
[root@rh7dev01 configs]# crm_attribute -l reboot -n db2hadr_db2cce_CCE_fal -G --quiet
Error performing operation: No such device or address
[root@rh7dev01 configs]# crm_attribute -t nodes -l reboot -n db2hadr_db2cce_CCE_fal -G --quiet
Error performing operation: No such device or address

**# WORKING QUERIES**
[root@rh7dev01 configs]# crm_attribute -l reboot -t nodes -n db2hadr_db2cce_CCE_fal -G --quiet
S0000000099.LOG
[root@rh7dev01 configs]# crm_attribute -t nodes -n db2hadr_db2cce_CCE_fal -G --quiet
S0000000099.LOG

**Comment by oalbrigt** [comment]
Oh. Thanks for the update.

I'll update the patch.

**Comment by oalbrigt** [comment]
I had a chat with one of the Pacemaker devs and apparently we should use -l forever instead of -t nodes. -t nodes does the same thing, but by accident.

**Comment by Delta-One-Two** [comment]
I can confirm that seems to work OK.

[root@rh7dev01 ~]# crm_attribute -l forever -n db2hadr_db2cce_CCE_fal -G --quiet
S0000000099.LOG

Thanks!

**Comment by oalbrigt** [comment]
Great.
