### ISSUE TITLE
heartbeat/podman remove container keeps anonymous volumes

### ISSUE THREAD

**Issue by dragon299** [ClusterLabs/resource-agents#1720]
When using the podman agent without "reuse" option, the container will be deleted after stop. If a container has anonymous volumes assosiated, those volumes will stay in the filesystem and will be re-created with new IDs during start. We ended with 600 volumes in our filesystem. 

I was able to fix this behavior by adding the "-v" option on "podman rm" in line 254. 
`Remove anonymous volumes associated with the container. This does not include named volumes created with podman volume create, or the --volume option of podman run and podman create.`

**Comment by oalbrigt** [comment]
Thanks.

I've made a patch to address this issue, and verified with some users of the agent that it shouldnt cause any issue for them.
