### ISSUE TITLE
ocf:heartbeat:nginx error

### ISSUE THREAD

**Issue by zingaro1972** [ClusterLabs/resource-agents#1772]
Hi,
after migrate the VM CLUSTERNODE01 from Oracle Linux 8 to ALmalinux 8 , the nginx cluster won't start ...
I compare the file /usr/lib/ocf/resource.d/heartbeat/nginx od CLUSTERNODE02 with the node CLUSTERNODE01 ( also migrated to Almalinux 2 moth ago wthout problem  ) and i noted the difference into the files on CLUSTERNODE02:

**OCF_RESKEY_httpd_default="/usr/sbin/httpd"
OCF_RESKEY_status10regex_default="Reading: [0-9]+ Writing: [0-9]+ Waiting: [0-9]+"

: ${OCF_RESKEY_httpd=${OCF_RESKEY_httpd_default}}
: ${OCF_RESKEY_status10regex=${OCF_RESKEY_status10regex_default}}****

these lines ore not present on /usr/lib/ocf/resource.d/heartbeat/nginx on CLUSTERNODE01 , after copy the files on CLUSTERNODE2 the pcs cluster starts withou errors ...

what is the differnce ?

the version of pcs , pacamaker and corosync are the same on 2 nodes ...

**Comment by zingaro1972** [comment]
ok, but i see into the lines  /usr/sbin/httpd !! the nginx binary correct is /usr/bin/nginx .. !!!
How it's can work ?. whit this syntax the service try to run httpd with nginx.conf files .. it's not possible and httpd return an error...

into the previous version of this service there aro not present this lines of code ...

**Comment by oalbrigt** [comment]
You can run `pcs resource debug-start --full <resource name>` to try to see why it fails. If these _default lines are missing it's probably because you need to set httpd=/usr/sbin/httpd and status10regex to the default value for it to work in the broken version.

**Comment by zingaro1972** [comment]
sorry but the service start correctly without the lines:
OCF_RESKEY_httpd_default="/usr/sbin/httpd"
OCF_RESKEY_status10regex_default="Reading: [0-9]+ Writing: [0-9]+ Waiting: [0-9]+"


whit the lines the service try to start : httpd and not nginx .....
 ERROR: AH00526: Syntax error on line 85 of /etc/httpd/conf.d/ssl.conf:

**Comment by zingaro1972** [comment]
into the previous release of the package resource-agent the line :
OCF_RESKEY_httpd_default="/usr/sbin/httpd"
OCF_RESKEY_status10regex_default="Reading: [0-9]+ Writing: [0-9]+ Waiting: [0-9]+

are not present and the service nginx start correctly ...
