### ISSUE TITLE
Processing failed monitor of rsc_azure-events:1

### ISSUE THREAD

**Issue by mabicca** [ClusterLabs/resource-agents#1802]
Hi everyone,

This is an SAP cluster, SLES 12 SP5, been seeing a few of these unknown errors in the logs:

```HOSTNAME pengine[7888]:  warning: Processing failed monitor of rsc_azure-events:1 on HOSTNAME: unknown error```
```HOSTNAME pengine[7888]:  warning: Processing failed monitor of rsc_SAPHanaTopology_CLU_HDB00:1 on HOSTNAME: unknown error```

Are there any references on what these might mean?

In this particular case I did find out a few things that I am getting fixed such as:
1) Duplicated hostnames in /etc/hosts with different uppercase/lowercase numbers like:
1.1.1.1 hostname
1.1.1.1 HOSTNAME
2) Wrong host mapping variables in the cluster configuration mapping the hostname to the wrong VM name.

Not sure if these errors could be related to those yet, but wanted to check if there are any reports about these.

Thank you!
-Marco

**Comment by oalbrigt** [comment]
That sounds like it's related to the mentioned configuration issues.

You can run `pcs resource debug-monitor --full <resource-name>` to find where in the code it fails (and if it uses the incorrect values).
