### ISSUE TITLE
RFC: blocking outgoing connections with portblock

### ISSUE THREAD

**Issue by chrboe** [ClusterLabs/resource-agents#1805]
Currently, the portblock resource agent deals only with incoming connections to destination ports.

We would like to extend this so that it can also block outgoing traffic.
Before I start sinking hours into this, I wanted to gather some early feedback on the proposal.

I see several possibilities for the API surface:

* Add a `source_ports` parameter to the resource agent. If this parameter is set, it would (also) block outgoing connections from these ports. I think this would be the most sensible approach overall, but probably also the most finicky to integrate into the current script.
* Add a `block_outgoing` boolean parameter, which would just block the same ports for incoming and outgoing connections. This would actually be the easiest for our specific use case, but I suspect this may not be in the general interest.
* Add a `direction` parameter (`in`/`out`) which defaults to the current behavior (= `in`). If this is set to `out`, it would *only* block outgoing connections. I don't personally love this because we would then need two separate portblock agents for our use case.

Any feedback would be appreciated, thanks.

**Comment by oalbrigt** [comment]
Maybe in/out/both could be an idea for direction?
