### ISSUE TITLE
ocf : heartbeat : pgsql - 3-node PG HA Cluster with async streaming replication

### ISSUE THREAD

**Issue by LeMerP** [ClusterLabs/resource-agents#1928]
Hey guys,

I just tried to setup a 3-node HA PG cluster, but if I am using more than one standby server (with async sl) the status of the standbys switch to "-INFINITY". I found a short explanation of the cause in the pgsql's ocf:
`# I can't determine which slave's data is newest in async mode.`
Please, could someone explain why it is not possible to determine the standby server with the closest data state / timeline compared to the primary server?

In Patroni, for example, there seems to be a parameter "check_timeline=true" that - at least - tries to determine the standby node with the latest data. (https://patroni.readthedocs.io/en/latest/replication_modes.html)

As I am working for about 5 years with a 2-node PG cluster controlled by Pacemaker / Corosync, I would really like to go on with it.

Thanks.

Kind regards,
Patrick

**Comment by oalbrigt** [comment]
pgsqlms might work better for your setup: https://github.com/ClusterLabs/PAF

And you can try mailing our users list to see if anyone has any tips there: http://oss.clusterlabs.org/mailman/listinfo/users
