### ISSUE TITLE
ocf:heartbeat:docker-compose fails with docker compose

### ISSUE THREAD

**Issue by minal3** [ClusterLabs/resource-agents#1974]
Hello,

I am using Ubuntu Server 24.04 as OS for my corosync/pacemaker cluster. docker-compose-v2 is the new APT package for docker compose, and syntax has slightly changed:

- Old syntax: **docker-compose**
- New syntax **docker compose**

ocf:heartbeat:docker-compose still uses the old syntax.  I had to edit RA code as follows:

```
OCF_RESKEY_binpath_default=/usr/bin/docker

if [ -r "$OCF_RESKEY_binpath" -a -x "$OCF_RESKEY_binpath" ]; then
	COMMAND="$OCF_RESKEY_binpath compose"
else
	COMMAND="$OCF_RESKEY_binpath_default compose"
fi
```
My docker-compose resource is running fine. I guess the above stands as a bug for users of Docker Compose V2.

Thanks,

**Comment by oalbrigt** [comment]
Does this work for "docker ps" and other calls as well?

If so we probably need to know the output from docker --version or similar to be able to detect version and add compose to all calls.

**Comment by oalbrigt** [comment]
Nevermind. I realized it's binpath isnt used for those calls.

**Comment by oalbrigt** [comment]
I've made a patch: https://github.com/ClusterLabs/resource-agents/pull/1975

Tell me if that solves the issue.

**Comment by minal3** [comment]
Just suggested a change for patch #1975.
