### ISSUE TITLE
azure-events fails to pull events

### ISSUE THREAD

**Issue by oalbrigt** [ClusterLabs/resource-agents#1986]
@MSSedusch We have an issue where azure-events isnt able to pull requests (on nodes that are not in any availability zones), but azure-events-az is working fine.

I tried a couple of quick changes (API version and increased timeout like in -az), but without any luck.

Do you have any suggestions for how to fix the agent?

```
# OCF_ROOT=/usr/lib/ocf HA_debug=1 /usr/lib/ocf/resource.d/heartbeat/azure-events monitor
azure-events(None)[2260]:	Oct 14 13:25:20 INFO: monitor: another node is pulling; retry in 1 seconds
azure-events(None)[2260]:	Oct 14 13:25:21 INFO: monitor: another node is pulling; retry in 1 seconds
azure-events(None)[2260]:	Oct 14 13:25:22 WARNING: monitor: exceeded maximum number of attempts (3) to pull events
```

**Comment by MSSedusch** [comment]
@rdeltcheva do you have a cluster that we can use to repro the issue?

**Comment by oalbrigt** [comment]
I was using the latest RHEL 9.4 build in my testing: resource-agents-4.10.0-52.el9

**Comment by rdeltcheva** [comment]
RA azure-events only supports VM deployed in Azure Availability Set. The successor of azure-events,  RA azure-events-az supports all combinations of VM deployments. We are not investing any more in RA azure-events. The recommendation is to switch to azure-events-az:  https://learn.microsoft.com/en-us/azure/sap/workloads/high-availability-guide-suse-pacemaker?tabs=msi#configure-pacemaker-for-azure-scheduled-events .

**Comment by oalbrigt** [comment]
Thank you for the information.
