### ISSUE TITLE
VirtualDomain: 

### ISSUE THREAD

**Issue by bootc** [ClusterLabs/resource-agents#364]
The commits 981c45d06095 and f00dcaf19467 fundamentally change how the VirtualDomain RA script manage domains with libvirt. While I agree that this changed functionality is a good improvement to the script, the changes are likely to break many existing configurations.

In all the examples I can see, including on http://www.linux-ha.org/wiki/VirtualDomain_(resource_agent), the domain XML file is kept under `/etc/libvirt/qemu/{domain}.xml` (e.g. `params config="/etc/libvirt/qemu/test.xml" hypervisor="qemu:///system"`). With this configuration, the XML file vanishes when the resource agent attempts to start the VM; it gets undefined first, then create attempts to start it from the no-longer-existing file.

**Comment by krig** [comment]
Closing this as this issue was discussed in #487.
