### ISSUE TITLE
Kamailio agent can't create PID file

### ISSUE THREAD

**Issue by ciroiriarte** [ClusterLabs/resource-agents#433]
I've tested the Kamailio agent, but it fails to create PID file when running as non root on CentOS 6:

kamailio: WARNING: <core> [daemonize.c:358]: daemonize(): unable to create pid file /var/run/kamailio.pid: Permission denied

[root@sip2 ~]# ls -ld /var/run/
drwxr-xr-x. 27 root root 4096 may 19 03:06 /var/run/

**Comment by seabres** [comment]
OK, i will implement the calculated PID file path in case of no pidfile parameter present.
This will happen at 7.1., because all repositories and testing environment is located at the company.

**Comment by dmuhamedagic** [comment]
Fixed. Thanks!
