### ISSUE TITLE
VirtualDomain: Does not tunnel migration over SSH correctly.

### ISSUE THREAD

**Issue by stevenhale** [ClusterLabs/resource-agents#489]
I don't know if I'm doing something completely wrong, but VirtualDomain doesn't seem to tunnel live migrations over SSH even when migration_transport="ssh".

I create a VirtualDomain resource like this:

```
# pcs resource create myVM ocf:heartbeat:VirtualDomain config=/mnt/gv0/etc/libvirt/qemu/myVM.xml hypervisor="qemu:///system" migration_transport="ssh" meta allow-migrate=true op monitor timeout="20" interval="10"
```

The config definitions and image storage are on a shared GlusterFS array under /mnt/gv0.  If I try to move the resource to a different node in the cluster, then VirtualDomain forms a command like this:

```
# virsh --connect=qemu:///system --quiet migrate --live myVM qemu+ssh://newNode/system
```

But setting the transport to qemu+ssh isn't actually enough to get it to use SSH.  I get the following error because it's not using SSH it's trying to do a native migration over TCP connection which is blocked by the firewall.

```
error: unable to connect to server at 'newhost:49152': No route to host
```

In order to tell virsh to use SSH I need to pass the "--tunnelled" parameter, which in turn then requires the "--p2p" parameter.  But VirtualDomain doesn't know about these two parameters and doesn't set them.

Is there some other way to get virsh to use SSH and I'm doing something wrong?  Or is it a bug?

I can make VirtualDomain work correctly for tunnelled live migration by adding "--tunnelled --p2p" to the appropriate line in the script.  But this isn't a real fix of course because it would break the script for anyone not using tunelling.  It seems to need some extra logic to decide when it needs to add "--tunnelled --p2p" based on the chosen migration transport.

This is using libvirt 1.1.1 from the CentOS 7 yum repository, and the latest version of VirtualDomain from here.

**Comment by dmuhamedagic** [comment]
@davidvossel David, you worked on VirtualDomain recently, what's your comment here?

**Comment by stevenhale** [comment]
Sorry for the late reply.

No, I didn't ask in the libvirt forum.  But I did spend a long time going over all the different options in the documentation to see if I was missing something.  Using subversion as an example, when you do a
...
% svn checkout svn+ssh://
...
it automatically knows to correctly use ssh.  So it does seem to be a fault with the design of libvirt that even when you specify "qemu+ssh://" that it doesn't work out what to do.  It should work out the migrate option to be used by itself depending on the transport you've indicated in the node address.

I agree a "migrate_options" parameter in VirtualDomain should get around the problem.

**Comment by dmuhamedagic** [comment]
On Thu, Jan 15, 2015 at 02:06:31AM -0800, stevenhale wrote:
> Sorry for the late reply.

No problem.

> So it does seem to be a fault with the design of libvirt that even when you specify "qemu+ssh://" that it doesn't work out what to do.  It should work out the migrate option to be used by itself depending on the transport you've indicated in the node address.

I'm not so sure. There could possibly be other factors. For
instance, in my test installation there's only:

params config=... migration_transport=ssh

The default hypervisor connect string:

# virsh --quiet uri
qemu:///system

**Comment by dmuhamedagic** [comment]
The migrate_options parameter should help with this.
