### ISSUE TITLE
For Cluster File System

### ISSUE THREAD

**Issue by gdvyas** [ClusterLabs/resource-agents#593]
I am using Cluster File System and it is mounted like NFS. 

In certain situation I may have to run the Master and Slave both on the same node. How can I give separate PG data directory for Master and Slave?

**Comment by dmuhamedagic** [comment]
On Wed, Apr 08, 2015 at 01:02:40AM -0700, Gaurang Vyas wrote:
> I am using Cluster File System and it is mounted like NFS. 

what is Cluster File System?

> In certain situation I may have to run the Master and Slave both on the same node. How can I give separate PG data directory for Master and Slave?  

this sounds more like a question for a ml. pls try
users@clusterlabs.org.

**Comment by gdvyas** [comment]
The Question is for pgsql script. (https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/pgsql)

1) http://ceph.com/  as a distributed cluster file system.
2) All the pgdata and postgresql config file stays on CEPH cluster.
3) Posgresql can run any of the node on COROSYNC cluster.
4) All the resources are free floating on corosync cluster.
5) In certain case it may be the case Postgres Master and Postgres Slave is running on the same node.
6) As OCF_RESKEY_pgdata is shared by both master and slave instance of Postgres, it will be a big problem.

**Comment by dmuhamedagic** [comment]
Please try with the mailing list?
