### ISSUE TITLE
iSCSILogicalUnit - No way to set iblock Parameters

### ISSUE THREAD

**Issue by sammcj** [ClusterLabs/resource-agents#610]
It appears there is no way to set the iblock parameters for iSCSILogicalUnit.
For example, if you want to set emulate_tpu=1, you can't!

This means you can't:
- Enable TRIM / Discard (emulate_tpu)
- Enable Compare and Write (emulate_caw)
- Enable Extended Write (emulate_3pc)

**Comment by sammcj** [comment]
Any ideas with this?
You can't even set the default as it's been hard-coded into the kernel: https://github.com/torvalds/linux/blob/d19d133e432248c9b3efa9c10dda5f050cbbcd72/include/target/target_core_base.h#L95

**Comment by dmuhamedagic** [comment]
On Thu, May 07, 2015 at 08:42:30PM -0700, Sam wrote:
> It appears there is no way to set the iblock parameters for iSCSILogicalUnit.
> For example, if you want to set emulate_tpu=1, you can't!
> 
> This means you can't:
> 
> - Enable TRIM / Discard (emulate_tpu)
> - Enable Compare and Write (emulate_caw)
> - Enable Extended Write (emulate_3pc)

@fghaas, what do you say?

**Comment by fghaas** [comment]
Sorry, only saw this now. I see the problem, and have no issue with the RA setting these params (after all, we have other RAs running `modprobe`), and we already have implementation specific params in the RA. So, no objections to a patch that introduces more `lio_*` parameters that can cover this functionality.

**Comment by ross-w** [comment]
Seems sensible, this one just bit me as well

**Comment by dmuhamedagic** [comment]
Can somebody produce a pull request.

**Comment by sammcj** [comment]
@dmuhamedagic 

Not perfect, but done https://github.com/ClusterLabs/resource-agents/pull/987
