### ISSUE TITLE
iSCSILogicalUnit tries to use 'tcm_node' command that is now deprecated

### ISSUE THREAD

**Issue by sammcj** [ClusterLabs/resource-agents#626]
lio-utils has been deprecated and removed in favour of targetcli in recent distributions (i.e. CentOS 7).

iSCSILogicalUnit is still using (or trying to use) tcm_node.py from the lio-utils package which is no longer maintained or available.

The reliance on tcm_node.py has leaves the iSCSITarget / iSCSILogicalUnit in a broken state with lio.

https://github.com/ClusterLabs/resource-agents/blob/master/heartbeat/iSCSILogicalUnit#L328

See: http://linux-iscsi.org/wiki/Lio-utils#Overview

**Comment by sammcj** [comment]
Relates to #637

**Comment by fghaas** [comment]
Well this is pretty much why there is an `lio-t` implementation option, which does rely on `targetcli`. If that option is broken (as #637) implies, then it needs fixing, but we can probably close this issue (#626) as the `lio` implementation's dependency on `tcm_node` is entirely expected (unless I'm missing something).

**Comment by sammcj** [comment]
@fghaas - I agree with you that lio-t indeed uses targetcli which indeed is what is required for RHEL / CentOS 7 and soon to be other distros as well.

Looking at the code there seems to be a lot of duplication where lio-t is essentially a copy-paste of lio with just a few commands replace.

I'm wondering if lio and lio-t both need to exist - given that tcm_node is deprecated I would think that the lio provider would simply always use targetcli as that is available on old and new distros alike.

Obviously this can't happen until #637 is resolved but does that sound like a good idea - please do tell me if you think I'm crazy or if I've missed something?

**Comment by fghaas** [comment]
@sammcj You can't assume that just because `targetcli` is preferred and `tcm_node` is deprecated, `targetcli` is indeed available everywhere and `tcm_node` is not. So yes, they both need to exist for the time being.

@dmuhamedagic, what do you think? Can we close this?

**Comment by dmuhamedagic** [comment]
On Mon, Jul 13, 2015 at 07:40:33AM -0700, Florian Haas wrote:
> @sammcj You can't assume that just because `targetcli` is preferred and `tcm_node` is deprecated, `targetcli` is indeed available everywhere and `tcm_node` is not. So yes, they both need to exist for the time being.
> 
> @dmuhamedagic, what do you think? Can we close this?

Yes, agreed.

**Comment by dmuhamedagic** [comment]
Closing.
