### ISSUE TITLE
iSCSITarget: default portal conflict

### ISSUE THREAD

**Issue by pemer** [ClusterLabs/resource-agents#630]
If you are useing the lio-t backend and the setting portal are defined != 0.0.0.0:3260 the targetd can not create a iscsi target, because the portal settings are in conflict.
At the moment the scripts send through targetcli following:

example:
```
targetcli /iscsi create iqn.2015-10.org.example.local
```

the targetd will create a default portal 0.0.0.0:3260. And this setting are in conflict, if in cluster a portal a defined.
The easiest way to fix the behaviour is, to set a global option that the targetd not creating a default  portal, if a user defined portal a configured.

example:
```
targetcli /iscsi set global auto_add_default_portal=false
```

**Comment by pemer** [comment]
this changes will fix this behavior from targetd

**Comment by sammcj** [comment]
+1 - this is quite annoying.

**Comment by fghaas** [comment]
I've commented on the PR; please amend the commit as suggested and then force-push to your fork — happy to merge after that unless there are any objections. Thanks for the patch!
