### ISSUE TITLE
ocf-tester fails in the galera resource agent

### ISSUE THREAD

**Issue by huikang** [ClusterLabs/resource-agents#644]
Hi,
I am trying to use your galera resource agent in the pacemaker cluster. The first step I am taking is to test the resource agent. However, when I run the ocf-tester command with the galera agent it report this error.

    $ ocf-tester -n galera -o wsrep_cluster_address="gcomm://pacemaker1,pacemaker2,pacemaker3" -o pid="/var/run/mysqld/mysqld.pid" -o config="/etc/mysql/my.cnf"  -o socket="/var/run/mysqld/mysqld.sock"    /usr/lib/ocf/resource.d/heartbeat/galera
Beginning tests for /usr/lib/ocf/resource.d/heartbeat/galera...
* Your agent does not support the notify action (optional)
* rc=1: Promote failed
* rc=1: Promote failed
ocf-exit-reason:Galera must be configured as a multistate Master/Slave resource.
promote
ocf-exit-reason:Failure, Attempted to promote Master instance of galera before bootstrap node has been detected.
Aborting tests

Did I miss anything in the command line? Thanks

**Comment by davidvossel** [comment]
The galera resource-agent isn't testable outside of a live Pacemaker cluster. The agent actually requires pacemaker's internal distributed database to work properly. If you are interested in seeing how I test this agent, view this scenario file. https://github.com/davidvossel/phd/blob/master/scenarios/galera-basic.scenario

**Comment by huikang** [comment]
Hi David
Thanks for your reply. Now I understand that I can not use ocf-tester to
test the galera resource agent.

There are 3 ubuntu 14 nodes in my clusters and I have installed pacemaker
and corosync. The output is like
----------------------
Last updated: Fri Jul 17 22:05:16 2015
Last change: Thu Jul 16 22:24:12 2015 via cibadmin on pacemaker3
Stack: corosync
Current DC: pacemaker1 (101) - partition with quorum
Version: 1.1.10-42f2063
3 Nodes configured
4 Resources configured

Online: [ pacemaker1 pacemaker2 pacemaker3 ]

----------------------

As there is no pcs in the ubuntu system, I have two questions regarding
running your galera scenario

1) Is it required to "./autogen.sh && ./configure && make install" the
entire package? Or can I just use the galera resource agent from
clusterlab's repo, plus customizing the galera-basic.scenario a bit (like
the PHD_ENV_nodes1)?

2) As I am new to crm and pcs, do you provide the equivalent crm command to
the pcs in the galera-basic.scenario?

Thanks.

**Comment by davidvossel** [comment]
----- Original Message -----
> Hi David
> Thanks for your reply. Now I understand that I can not use ocf-tester to
> test the galera resource agent.
> 
> There are 3 ubuntu 14 nodes in my clusters and I have installed pacemaker
> and corosync. The output is like
> ----------------------
> Last updated: Fri Jul 17 22:05:16 2015
> Last change: Thu Jul 16 22:24:12 2015 via cibadmin on pacemaker3
> Stack: corosync
> Current DC: pacemaker1 (101) - partition with quorum
> Version: 1.1.10-42f2063
> 3 Nodes configured
> 4 Resources configured
> 
> Online: [ pacemaker1 pacemaker2 pacemaker3 ]
> 
> ----------------------
> 
> As there is no pcs in the ubuntu system, I have two questions regarding
> running your galera scenario
> 
> 1) Is it required to "./autogen.sh && ./configure && make install" the
> entire package? Or can I just use the galera resource agent from
> clusterlab's repo, plus customizing the galera-basic.scenario a bit (like
> the PHD_ENV_nodes1)?

You'll likely have to make install the resource-agents on every node. The
galera resource-agent depends on some mysql common files. There are some
new ocf library calls the galera agent makes use of as well. Giving that
pacemaker 1.1.10 is in use, I'm really doubting that the resource-agents
package shipped in ubuntu 14 has all the changes that would be necesssary
for you to simply copy the galera agent over directly from github.


> 2) As I am new to crm and pcs, do you provide the equivalent crm command to
> the pcs in the galera-basic.scenario?

unfortunately, I am not well versed in crmsh. There is however a good cheat
sheet available to convert crmsh commands to the pcs equivalent.
https://github.com/ClusterLabs/pacemaker/blob/master/doc/pcs-crmsh-quick-ref.md

**Comment by dmuhamedagic** [comment]
As noted, a ms agent typically cannot be tested with ocf-tester.
