### ISSUE TITLE
Is it mistake or some workaround in set_master_score?

### ISSUE THREAD

**Issue by m-ly4** [ClusterLabs/resource-agents#655]
I found, that update of pgsql master attribute called for node $target (pgsql resource agent)
Is it mistake and $1 should be used or it is some sort of w/a?

```bash
set_master_score()
{
    local current_score

    current_score=`$CRM_ATTR_REBOOT -N "$1" -n "master-$3" -G -q 2>/dev/null`
    if [ -n "$current_score" -a "$current_score" != "$2" ]; then
        ocf_log info "Changing $3 master score on $1 : $current_score->$2."
>>>     exec_with_retry 0 $CRM_ATTR_REBOOT -N "$target" -n "master-$3" -v "$2"

    fi
    return 0
}
```

**Comment by dmuhamedagic** [comment]
Looks like a bug to me too. @t-matsuo, Takatoshi-san, what is
your opinion?

**Comment by higashik** [comment]
Hi, I am a colleague of @t-matsuo .
(Takatoshi-san was transferred to another company.)

I think this is Bug too.
But, the "target" variable has been defined in all of the calling function.
So, it was operating normally.

I would like to fix it.

**Comment by higashik** [comment]
I create a new pull request #663 .
Would you please check it and merge?

**Comment by t-matsuo** [comment]
It's a bug !!
Thanks for your report and fixing it.

**Comment by dmuhamedagic** [comment]
Pull request merged.
