### ISSUE TITLE
heartbeat/pgsql - return code override in pgsql_real_start() if replication_slot_name is defined

### ISSUE THREAD

**Issue by sobolev-es** [ClusterLabs/resource-agents#666]
Commit d67c0ae (pgsql: Support replication slots) overrides return code of pgsql_real_monitor() in pgsql_real_start() function when replication_slot_name is defined.
So pgsql_real_start() never returns $OCF_RUNNING_MASTER and pgsql_promote() failed with error "Can't start PostgreSQL as primary on promote." on cluster startup. 

Fix:
--- pgsql.old   2015-08-25 14:54:27.733793980 +0300
+++ pgsql       2015-08-25 11:20:25.462804160 +0300
@@ -654,8 +654,7 @@
     # creating slot on the slave node is in preparation for failover.
     if use_replication_slot; then
         create_replication_slot
-        rc=$?
-        if [ $rc -eq $OCF_ERR_GENERIC ]; then
+        if [ $? -eq $OCF_ERR_GENERIC ]; then
             ocf_exit_reason "PostgreSQL can't create replication_slot."
             return $OCF_ERR_GENERIC
         fi

PS: restart_on_promote="true"

**Comment by dmuhamedagic** [comment]
On Tue, Aug 25, 2015 at 05:40:03AM -0700, sobolev-es wrote:
> Commit d67c0ae (pgsql: Support replication slots) overrides return code of pgsql_real_monitor() in pgsql_real_start() function when replication_slot_name is defined.
> So pgsql_real_start() never returns $OCF_RUNNING_MASTER and pgsql_promote() failed with error "Can't start PostgreSQL as primary on promote." on cluster startup. 

Good catch! Could you please create a pull request too?

**Comment by dmuhamedagic** [comment]
This was merged. Thanks!
