### ISSUE TITLE
Filesystem: proper FSTYPE for overlayfs

### ISSUE THREAD

**Issue by salortiz** [ClusterLabs/resource-agents#676]
The Filesystem RA uses `overlayfs` in its tests but the currently supported fstype in linux is `overlay` instead. So the logic in `set_blockdevice_var()` fails.

[root@erika ~]# uname -a
Linux erika 4.1.6-200.fc22.x86_64  SMP Mon Aug 17 19:54:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[root@erika ~]# cat /proc/filesystems 
...
nodev	**overlay**
...

**Comment by dmuhamedagic** [comment]
There's actually both overlay and overlayfs, apparently the former replaced the latter:

joe-1:~ # find /lib -type f -name overl* 
/lib/modules/3.12.49-11-default/kernel/fs/overlayfs/overlay.ko
/lib/modules/3.12.49-11-default/kernel/fs/overlayfs-old/overlayfs.ko

**Comment by dmuhamedagic** [comment]
Added overlay now. Thanks for reporting.
