### ISSUE TITLE
docker RA image validation incorrect

### ISSUE THREAD

**Issue by jarredcg** [ClusterLabs/resource-agents#678]
in the docker RA's image_exists() function, the image name is grabbed from OCF_RESKEY_name. The name is the container (and optionally the resource name) -- not the image name. image_exists should grab OCF_RESKEY_image instead. This prevents docker resources from starting properly.

**Comment by HideoYamauchi** [comment]
I think so, too.
I submit the next correction.

 * https://github.com/ClusterLabs/resource-agents/pull/668

**Comment by guessi** [comment]
@jarredcg , nice catch, thanks !!

wait for merge @HideoYamauchi 's #668

**Comment by guessi** [comment]
Hi @jarredcg ,
can we close this topic now?

it have been fixed after PR#668

**Comment by krig** [comment]
Closing since it is fixed by #668.
