### ISSUE TITLE
Add support for virsh migrate-setspeed

### ISSUE THREAD

**Issue by digimer** [ClusterLabs/resource-agents#679]
Re: http://clusterlabs.org/pipermail/users/2015-September/001387.html

Please add support for 'virsh migrate-setspeed' to the vm.sh RA. Something like; 'setspeed="75MiB"'?

**Comment by isavcic** [comment]
https://github.com/ClusterLabs/resource-agents/pull/629

**Comment by dmuhamedagic** [comment]
Merged.
