### ISSUE TITLE
sg_persist: READ_KEYS and READ_RESERVATION fail if run through ocf_run on Ubuntu 12.04

### ISSUE THREAD

**Issue by zmx** [ClusterLabs/resource-agents#689]
In sg_persist_get_status(), I must remove ocf_run for these two lines to make it work on Ubuntu 12.04. 

        # READ_KEYS=`ocf_run $SG_PERSIST --in --read-keys $dev 2>&1`
        READ_KEYS=`$SG_PERSIST --in --read-keys $dev 2>&1`

                # READ_RESERVATION=`ocf_run $SG_PERSIST --in --read-reservation $dev 2>&1`
                READ_RESERVATION=`$SG_PERSIST --in --read-reservation $dev 2>&1`

**Comment by dmuhamedagic** [comment]
This is obviously a bug, don't see ocf_run dumping anything to stdout.

**Comment by dmuhamedagic** [comment]
pr #731 fixes this.

**Comment by dmuhamedagic** [comment]
Fixed. Thanks for reporting!
