### ISSUE TITLE
iSCSITarget attempts to create iqn multiple times for every portal

### ISSUE THREAD

**Issue by akeyjadu** [ClusterLabs/resource-agents#690]
When iSCSITarget has multiple portals specified eg.
pcs -f drbd01 resource create iscsi-drbd0-target1 ocf:heartbeat:iSCSITarget implementation="lio-t" iqn="iqn.2015-09.example.com:drbd0" portals="10.80.0.101:3260 10.81.0.101:3260" op monitor interval="30s"

for every portal specified the script will attempt to create new target and will fail on the 2nd attempt because targetcli will error due to the fact the target already exists.

Here's a pull request that fixes this: https://github.com/ClusterLabs/resource-agents/pull/687

**Comment by dmuhamedagic** [comment]
Pull request merged. Thanks!
