### ISSUE TITLE
iSCSILogicalUnit - relationship of scsi_sn to vpd_unit_serial and SCSI ID confusing

### ISSUE THREAD

**Issue by sammcj** [ClusterLabs/resource-agents#726]
It is not clear that resource agent parameter of `scsi_sn` is actually what sets the configfs value for `vpd_unit_serial` which is what relates to / forms the `SCSI ID` for clients.

In order to maintain a consistent value for the `SCSI ID` between failovers (which is requiredf or Xen/XenServer) you must ensure the following parameters are set:
- `scsi_sn`
- `lun`
- `lio_iblock`

If all 3 of these are not specified the resulting `SCSI ID` can and does change, at least when managing multiple LUNs failing between hosts.

I think the most confusing part of all of this is the difference in naming / terminology around what vpd_unit_serial:
- The resource agent talks about `scsi_sn` (which actually sets the `vpd_unit_serial` in ConfigFS)
- ConfigFS talks about `vpd_unit_serial`.
- Xen / iSCSI initiators talk about `SCSI ID` (which is a combination formed from example below)

The `SCSI ID` is comprised of: 
- NAA 6, IEEE Company_id: 0x1405
- Vendor Specific Identifier: 0xbff3f42a4
- Vendor Specific Identifier Extension: 0x9d84cfcb64e2b933

Which is an ID of: 0x6001405bff3f42a49d84cfcb64e2b933

---

Example configuration:

```
primitive iscsi_lun_r0 iSCSILogicalUnit \
  params target_iqn="iqn.2003-01.org.linux-iscsi.s1-san5.x8664:sn.a70cc7bf74e5" scsi_sn=22be7863 lun=1 lio_iblock=0 path="/dev/drbd0" allowed_initiators="iqn.2015-05.com.example:516b8f8c" implementation=lio-t
```

While our instance of this issue has been resolved I have been asked by the target-devel mailing list to log a bug against resource-agents to add some additional clarification / visibility.

Here is the full discussion from the mailing list: http://comments.gmane.org/gmane.linux.scsi.target.devel/10617

**Comment by fghaas** [comment]
I understand that it's confusing, but can you please explain what you actually want fixed here? Throw `OCF_ERR_CONFIGURED` if one of `scsi_sn`, `lun`, and `lio_iblock` isn't set?

**Comment by sammcj** [comment]
I don't have any answers as such but I think the terminology needs to be clarified at least.

For example why is `vid_unit_serial` called `scsi_sn` in the RA?

**Comment by sammcj** [comment]
Or, perhaps in the RA descriptions there could be a note as to what items are required to persist the `SCSI ID` between failovers, however I am worried that perhaps that level of documentation could be too deep for in the RA itself?

**Comment by dmuhamedagic** [comment]
So? Improve meta-data?

**Comment by hunter86bg** [comment]
I think that if scsi_sn , we got a bigger issue.
The described below was observed some time ago and may not be valid any more (but I seriously doubt on that):
RHEL7.5 /SLES12.4
2 clusters with iSCSI ontop of DRBD are configured identically and scsi_sn is not configured.
When the client mounted the LUNs from the first cluster multipath aggregated the links (as expected) into a mpath with 2 paths.
Once the LUN from the second cluster (SLES) was added , multipath aggregated the 2 new paths into the same old mpath device - causing 2 separate luns to be viewed as a 1 single device with 4 paths to it.

As you can see this is quite risky.
Should I open a new issue , as we need to ensure that scsi_id is either:
A) mandatory field
B) we assign some random value to scsi_id during the initial creation of the ocf:heartbeat:iSCSILogicalUnit resource

Maybe this is fixed , but if not - we need to act appropriately.
