### ISSUE TITLE
fslib.fs is_mounted does not work with linux 3.x nfs

### ISSUE THREAD

**Issue by elacour** [ClusterLabs/resource-agents#74]
As of linux 3.2.0 at least, an nfs mounted directory is reported in /proc/mounts with a trailing "/":

```
192.168.3.56:/srv/nfs/fweb/ /srv/fweb nfs4 [...]
```

thus a resource configured with:

```
params name="fweb_fs" mountpoint="/srv/fweb" host="192.168.3.56" export="/srv/nfs/fweb" fstype="nfs" [...]
```

ends with a condition like:

```
-n 192.168.3.56:/srv/nfs/fweb/ -a 192.168.3.56:/srv/nfs/fweb/ = 192.168.3.56:/srv/nfs/fweb
```

which does not returns the expected result:

```
<err>    filesystem:fweb_fs: 192.168.3.56:/srv/nfs/fweb is not mounted on /srv/fweb
```

here is a quick patch:

<pre>--- tmp/fs-lib.sh  2012-04-26 12:38:39.000000000 +0200
+++ fs-lib.sh   2012-04-26 12:57:44.000000000 +0200
@@ -264,6 +264,10 @@
 
    real_device "$1"
    dev="$REAL_DEVICE"
+   # On recent Linux versions, nfs mountpoint have a trailing / in
+   # /proc/mounts
+   dev="${dev%/}"
+
    if [ -z "$dev" ]; then
        ocf_log err "$OCF_RESOURCE_INSTANCE: is_mounted: Could not match $1 with a real device"
        return $OCF_ERR_ARGS
@@ -291,6 +295,11 @@
        real_device "$tmp_dev"
        tmp_dev="$REAL_DEVICE"
 
+       # On recent Linux versions, nfs mountpoint have a trailing / in
+       # /proc/mounts
+       tmp_dev="${tmp_dev%/}"
+
+
        # XXX fork/clone warning XXX
        # Mountpoint from /proc/mounts containing spaces will
        # have spaces represented in octal.  printf takes care
</pre>

**Comment by nrwahl2** [comment]
Seems like this was fixed at some point along the line?

https://github.com/ClusterLabs/resource-agents/blob/master/rgmanager/src/resources/utils/fs-lib.sh.in#L515-L517

**Comment by oalbrigt** [comment]
Closing. Reopen if this is still an issue.
