### ISSUE TITLE
resource-agents/heartbeat/iscsi works incorrectly with multipath scheme

### ISSUE THREAD

**Issue by berlevdv** [ClusterLabs/resource-agents#744]
I have one target with two portals (for multipath):
10.0.1.1 iqn.1998-01.com.mycompany:myserver.storage
10.0.2.1 iqn.1998-01.com.mycompany:myserver.storage

Create two resorce to controll iscsi initiator:
pcs resource create iscsi-initiator10011 iscsi portal="10.0.1.1:3260" target="iqn.1998-01.com.mycompany:myserver.storage" op start interval="0" timeout="120s" op stop
interval="0" timeout="120s" op monitor interval="120s" timeout="30s" clone ordered=true
interleave=true

pcs resource create iscsi-initiator10021 iscsi portal="10.0.2.1:3260" target="iqn.1998-01.com.mycompany:myserver.storage" op start interval="0" timeout="120s" op stop
interval="0" timeout="120s" op monitor interval="120s" timeout="30s" clone ordered=true
interleave=true

iscsi resource agent from master branch connect to only one portal of target, because function open_iscsi_get_session_id() ignores portal and function open_iscsi_monitor() returns "0: target running (logged in)" if the target is connected through at least one portal.

To fix it I change lines on function open_iscsi_get_session_id():
local portal="$2"
$iscsiadm -m session 2>/dev/null |
                grep -E "$target($|[[:space:]])" |
                grep -E "] $portal" |
                awk '{print $2}' | tr -d '[]'

And add parameter "$OCF_RESKEY_portal" to calls of function open_iscsi_get_session_id()

**Comment by oalbrigt** [comment]
Please create a pull request with the fix.

**Comment by oalbrigt** [comment]
Merged.

Thank you for your patch.
