### ISSUE TITLE
iSCSI_Target cannot add target with lio-t

### ISSUE THREAD

**Issue by d-zalewski** [ClusterLabs/resource-agents#763]
Running pacemaker-1.1.14 and resource-agents-3.9.7 on Centos 7.2.1511

`pcs resource create iSCSI_Target ocf:heartbeat:iSCSITarget iqn=iqn.2003-01.org.linux-iscsi.ams-ceph.x8664:sn.2d1f18795f83 portals:172.16.20.54:3260 implementation=lio-t additional_parameters="MaxConnections=100 AuthMethod=None InitialR2T=No MaxOutstandingR2T=64"`

```
[root@ams-osd0 ~]# pcs status
Cluster name: ceph-iscsi
Last updated: Sat Feb 13 22:54:05 2016		Last change: Sat Feb 13 22:53:00 2016 by root via cibadmin on ams-osd0
Stack: corosync
Current DC: ams-osd0 (version 1.1.14-1.el7.centos.1-70404b0) - partition with quorum
2 nodes and 2 resources configured

Online: [ ams-osd0 ams-osd1 ]

Full list of resources:

 iSCSI_VIP	(ocf::heartbeat:IPaddr2):	Started ams-osd0
 iSCSI_Target	(ocf::heartbeat:iSCSITarget):	Stopped


**Failed Actions:
* iSCSI_Target_start_0 on ams-osd0 'unknown error' (1): call=48, status=complete, exitreason='none',
    last-rc-change='Sat Feb 13 22:53:01 2016', queued=0ms, exec=504ms
* iSCSI_Target_start_0 on ams-osd1 'unknown error' (1): call=45, status=complete, exitreason='none',
    last-rc-change='Sat Feb 13 22:53:00 2016', queued=0ms, exec=463ms**



PCSD Status:
  ams-osd0: Online
  ams-osd1: Online

Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled

```

**Comment by dmuhamedagic** [comment]
On Sat, Feb 13, 2016 at 01:57:06PM -0800, d-zalewski wrote:
> I'm trying to add a iSCSI_Target with lio-t using below command:
> 
> `pcs resource create iSCSI_Target ocf:heartbeat:iSCSITarget iqn=iqn.2003-01.org.linux-iscsi.ams-ceph.x8664:sn.2d1f18795f83 portals:172.16.20.54:3260 implementation=lio-t additional_parameters="MaxConnections=100 AuthMethod=None InitialR2T=No MaxOutstandingR2T=64"`
> 
> 
> ```
> [root@ams-osd0 ~]# pcs status
> Cluster name: ceph-iscsi
> Last updated: Sat Feb 13 22:54:05 2016		Last change: Sat Feb 13 22:53:00 2016 by root via cibadmin on ams-osd0
> Stack: corosync
> Current DC: ams-osd0 (version 1.1.14-1.el7.centos.1-70404b0) - partition with quorum
> 2 nodes and 2 resources configured
> 
> Online: [ ams-osd0 ams-osd1 ]
> 
> Full list of resources:
> 
>  iSCSI_VIP	(ocf::heartbeat:IPaddr2):	Started ams-osd0
>  iSCSI_Target	(ocf::heartbeat:iSCSITarget):	Stopped
> 
> 
> **Failed Actions:
> * iSCSI_Target_start_0 on ams-osd0 'unknown error' (1): call=48, status=complete, exitreason='none',
>     last-rc-change='Sat Feb 13 22:53:01 2016', queued=0ms, exec=504ms
> * iSCSI_Target_start_0 on ams-osd1 'unknown error' (1): call=45, status=complete, exitreason='none',
>     last-rc-change='Sat Feb 13 22:53:00 2016', queued=0ms, exec=463ms**
> 
> 
> 
> PCSD Status:
>   ams-osd0: Online
>   ams-osd1: Online
> 
> Daemon Status:
>   corosync: active/enabled
>   pacemaker: active/enabled
>   pcsd: active/enabled
> 
> ```

This is really a question for the ML (users@clusterlabs.org). We
can then discuss, look at the logs, and finally establish there
whether it's a configuration issue or really a bug in the RA.
Thanks!

**Comment by dmuhamedagic** [comment]
Just like for the previous issue you opened:

This is really a question for the ML (users@clusterlabs.org). We
can then discuss, look at the logs, and finally establish there
whether it's a configuration issue or really a bug in the RA.
Thanks!

**Comment by d-zalewski** [comment]
it seems ok after I've done pcs resource cluster stop -all && pcs resource cluster start --all.

I will post it to user list.

**Comment by sunnoy** [comment]
I meet this ，will try you command
