### ISSUE TITLE
iSCSILogicalUnit cannot add lun with lio-t

### ISSUE THREAD

**Issue by d-zalewski** [ClusterLabs/resource-agents#764]
Running pacemaker-1.1.14 and resource-agents-3.9.7 on Centos 7.2.1511

```
pcs resource create iSCSI_LUN_hgst ocf:heartbeat:iSCSILogicalUnit target_iqn=iqn.2003-01.org.linux-iscsi.ams-ceph.x8664:sn.2d1f18795f83 scsi_sn=633c5643 lun=1 lio_iblock=0 path=/dev/rbd/hgst/hgst implementation=lio-t

[root@ams-osd0 ~]# pcs status
Cluster name: ceph-iscsi
Last updated: Sat Feb 13 22:56:58 2016		Last change: Sat Feb 13 22:55:20 2016 by root via cibadmin on ams-osd0
Stack: corosync
Current DC: ams-osd0 (version 1.1.14-1.el7.centos.1-70404b0) - partition with quorum
2 nodes and 3 resources configured

Online: [ ams-osd0 ams-osd1 ]

Full list of resources:

 iSCSI_VIP	(ocf::heartbeat:IPaddr2):	Started ams-osd0
 iSCSI_Target	(ocf::heartbeat:iSCSITarget):	Stopped
 iSCSI_LUN_hgst	(ocf::heartbeat:iSCSILogicalUnit):	Stopped

Failed Actions:
* iSCSI_Target_start_0 on ams-osd0 'unknown error' (1): call=48, status=complete, exitreason='none',
    last-rc-change='Sat Feb 13 22:53:01 2016', queued=0ms, exec=504ms
* iSCSI_LUN_hgst_start_0 on ams-osd0 'unknown error' (1): call=54, status=complete, exitreason='none',
    last-rc-change='Sat Feb 13 22:55:21 2016', queued=0ms, exec=370ms
* iSCSI_Target_start_0 on ams-osd1 'unknown error' (1): call=45, status=complete, exitreason='none',
    last-rc-change='Sat Feb 13 22:53:00 2016', queued=0ms, exec=463ms
* iSCSI_LUN_hgst_start_0 on ams-osd1 'unknown error' (1): call=51, status=complete, exitreason='none',
    last-rc-change='Sat Feb 13 22:55:20 2016', queued=0ms, exec=330ms


PCSD Status:
  ams-osd0: Online
  ams-osd1: Online

Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled
```

**Comment by dmuhamedagic** [comment]
On Sat, Feb 13, 2016 at 01:59:00PM -0800, d-zalewski wrote:
> Running pacemaker-1.1.14 and resource-agents-3.9.7 on Centos 7.2.1511
> 
> pcs resource create iSCSI_LUN_hgst ocf:heartbeat:iSCSILogicalUnit target_iqn=iqn.2003-01.org.linux-iscsi.ams-ceph.x8664:sn.2d1f18795f83 scsi_sn=633c5643 lun=1 lio_iblock=0 path=/dev/rbd/hgst/hgst implementation=lio-t
> 
> [root@ams-osd0 ~]# pcs status
> Cluster name: ceph-iscsi
> Last updated: Sat Feb 13 22:56:58 2016		Last change: Sat Feb 13 22:55:20 2016 by root via cibadmin on ams-osd0
> Stack: corosync
> Current DC: ams-osd0 (version 1.1.14-1.el7.centos.1-70404b0) - partition with quorum
> 2 nodes and 3 resources configured
> 
> Online: [ ams-osd0 ams-osd1 ]
> 
> Full list of resources:
> 
>  iSCSI_VIP	(ocf::heartbeat:IPaddr2):	Started ams-osd0
>  iSCSI_Target	(ocf::heartbeat:iSCSITarget):	Stopped
>  iSCSI_LUN_hgst	(ocf::heartbeat:iSCSILogicalUnit):	Stopped
> 
> Failed Actions:
> * iSCSI_Target_start_0 on ams-osd0 'unknown error' (1): call=48, status=complete, exitreason='none',
>     last-rc-change='Sat Feb 13 22:53:01 2016', queued=0ms, exec=504ms
> * iSCSI_LUN_hgst_start_0 on ams-osd0 'unknown error' (1): call=54, status=complete, exitreason='none',
>     last-rc-change='Sat Feb 13 22:55:21 2016', queued=0ms, exec=370ms
> * iSCSI_Target_start_0 on ams-osd1 'unknown error' (1): call=45, status=complete, exitreason='none',
>     last-rc-change='Sat Feb 13 22:53:00 2016', queued=0ms, exec=463ms
> * iSCSI_LUN_hgst_start_0 on ams-osd1 'unknown error' (1): call=51, status=complete, exitreason='none',
>     last-rc-change='Sat Feb 13 22:55:20 2016', queued=0ms, exec=330ms
> 
> 
> PCSD Status:
>   ams-osd0: Online
>   ams-osd1: Online
> 
> Daemon Status:
>   corosync: active/enabled
>   pacemaker: active/enabled
>   pcsd: active/enabled


Just like for the previous issue you opened:

This is really a question for the ML (users@clusterlabs.org). We
can then discuss, look at the logs, and finally establish there
whether it's a configuration issue or really a bug in the RA.
Thanks!

**Comment by d-zalewski** [comment]
it seems ok after I've done pcs resource cluster stop -all && pcs resource cluster start --all.

I will post it to user list.
