### ISSUE TITLE
"make install" eventually fails due to existing /usr/lib/ocf/resource.d/heartbeat/.ocf-binaries for which configure prefix seems to be ignored

### ISSUE THREAD

**Issue by krichter722** [ClusterLabs/resource-agents#777]
`sudo make install` fails in a fresh clone if `/usr/lib/ocf/resource.d/heartbeat/.ocf-binaries` is present (with `ln: failed to create symbolic link ‘/usr/lib/ocf/resource.d/heartbeat/.ocf-binaries’: File exists`) because the `configure` prefix seems to be ignored.

experienced with v3.9.7-17-ga0af930

**Comment by pbraun9** [comment]
Same here 4 years after, against v4.5.0.  I need to run this first
```rm -f /usr/lib/ocf/resource.d/heartbeat/.ocf-binaries /usr/lib/ocf/resource.d/heartbeat/.ocf-directories /usr/lib/ocf/resource.d/heartbeat/.ocf-returncodes /usr/lib/ocf/resource.d/heartbeat/.ocf-shellfuncs```

**Comment by oalbrigt** [comment]
PR to fix this: https://github.com/ClusterLabs/resource-agents/pull/1520
