### ISSUE TITLE
exportfs: IPv6 support patch

### ISSUE THREAD

**Issue by lgrawet** [ClusterLabs/resource-agents#786]
Here is a patch to support IPv6. exportfs returns IPs without the [] around client IP.
[exportfs-ipv6.txt](https://github.com/ClusterLabs/resource-agents/files/189607/exportfs-ipv6.txt)

**Comment by lgrawet** [comment]
Small fix for "*" aka <world> exports
[exportfs-ipv6-v2.txt](https://github.com/ClusterLabs/resource-agents/files/206419/exportfs-ipv6-v2.txt)

**Comment by krig** [comment]
Could you submit this as a pull request instead?

Fork the resource-agents repository, then clone your copy, create a branch, apply the patch, commit and push to `lgrawet/resource-agents`. Then you can go to `ClusterLabs/resource-agents` in the github UI and there should be a button to create a pull request from your branch. That way, you'll show up as the author, reviewers can comment on lines in the patch etc.

**Comment by oalbrigt** [comment]
Fixed in: https://github.com/ClusterLabs/resource-agents/pull/828
