### ISSUE TITLE
make hangs

### ISSUE THREAD

**Issue by anuphalarnkar** [ClusterLabs/resource-agents#830]
**OS**: RHEL 7.2
**Arch**: PPC64LE
**uname -a** => Linux xxxxxxx 3.10.0-229.ael7b.ppc64le #1 SMP Fri Jan 30 12:03:50 EST 2015 ppc64le ppc64le ppc64le GNU/Linux
**Attachment**: Logs for configure and make attached

**Steps:**
./autogen.sh  is successful
./configure is successful
make does not fail... but just hangs. 

**Summary of log output where it hangs:**
Making all in man
gmake[3]: Entering directory `/root/rhelHA/tarballs/resource-agents/doc/man'
OCF_ROOT=. OCF_FUNCTIONS_DIR=../../heartbeat ../../heartbeat/AoEtarget meta-data > metadata-AoEtarget.xml
/usr/bin/xsltproc --novalid \
--stringparam package resource-agents \
--stringparam version 3.9.7.104-a96e \
--output ocf_heartbeat_AoEtarget.xml \
./ra2refentry.xsl metadata-AoEtarget.xml
/usr/bin/xsltproc \
--xinclude \
http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl ocf_heartbeat_AoEtarget.xml

**Possible reason**:
Not sure if this is because of validation error for xsltproc ?? 

Will be grateful for any inputs on above issue.

Thanks in advance,
Anup 

[ra_make.txt](https://github.com/ClusterLabs/resource-agents/files/328122/ra_make.txt)
[ra_configure.txt](https://github.com/ClusterLabs/resource-agents/files/328123/ra_configure.txt)

Halarnkar

**Comment by mbaldessari** [comment]
xsltproc is likely trying to fetch stuff from the network and failing for whatever reason. Just use --nonet and make sure that you install docbook on the host and register it into xml catalog

**Comment by anuphalarnkar** [comment]
@mbaldessari  Thanks a lot!! Installing docbook related packages solved the issue.
