### ISSUE TITLE
Postgresql slave unexpectedly starts after failover

### ISSUE THREAD

**Issue by anteyk** [ClusterLabs/resource-agents#851]
Hi,
We've faced with following issue:
Imagine cluster with 7 nodes (1 of them (node2) is powered off). There is postgres cluster on two nodes: node5 (master) and node7 (slave).  node1, node2, node3, node5 are behind one ethernet switch (s1), node4 is behind another one (s2), node6 and node7 are behind third one (s3). 
This night S1 started to work bad with random connectivity loss between s1 and other switches, but with normal connectivity within s1 nodes (node1, node3, node5)
Eventually pg master moved to node7 and pg on node5 was shuted down. But node5 became a slave (with proper recovery.conf) and started! In corosync.log there is record showed that pacemaker removed  PGSQL.lock file himself: "INFO: Removing /var/lib/pgsql/tmp/PGSQL.lock". As I see in resource it can occur when there is no slaves for that node. Am I right? It possible that slave became offline for that node as connectivity with node4, node6, node7 is lost. How can we avoid this behaviour in future?
Thank you!

**Comment by anteyk** [comment]
Hi, is there something, that I should add to issue description?

**Comment by kskmori** [comment]
It is hard to tell what's going on without your configs and logs, but in general, 

> node5 was shuted down. node5 became a slave (with proper recovery.conf) and started!

Starting the cluster when the OS startup automatically is not recommended. Instead it should be started after an operator make sure that the all failures are healed, and do the proper recovery steps of the database every time. That what I always do.

**Comment by anteyk** [comment]
Thank you for response and sorry for delay.
There wasn't node 5 shutdown - pacemaker only shuted down postgresql on that node.
Here is mspgqsql [config and constraints](https://gist.github.com/anteyk/254ca0e6e31be73d3cf6c2746c9dfd18)
And log files for failure time

[node5.txt](https://github.com/ClusterLabs/resource-agents/files/519640/node5.txt)
[node7.txt](https://github.com/ClusterLabs/resource-agents/files/519641/node7.txt)

**Comment by kskmori** [comment]
I still don't see what's going on exactly without the logs in the DC nodes and the full config (not the excerpt), but it sounds like a general Pacemaker configuration issue.

Do you have configured the stonith and quorum? If you have configured them properly, then the nodes in the minority partition should get fenced and never comes up when some switches are going wrong. If all partitions have got the minority (this is probably your case) then, (depending on the no-quorum-policy parameter but usually) all resource should be stopped and not be failed over. Having no-quorum-policy=freeze  may prevent restarting the resources after the network healed but I'm not sure that that's what you want.

**Comment by anteyk** [comment]
It's looks that in my case really all partitions got the minority. 
Sorry, but I don't understand what exact logs I have to attach? For all nodes in the cluster or something else? 
In attachement full cluster config. So there is no STONITH device and no-quorum-policy=stop
[cluster_config.txt](https://github.com/ClusterLabs/resource-agents/files/529227/cluster_config.txt)
