### ISSUE TITLE
VirtualDomain: New resource attribute "start_scripts"

### ISSUE THREAD

**Issue by berlevdv** [ClusterLabs/resource-agents#856]
Hello, dear developers and administrators!

I use VirtualDomain in a cluster of virtual machines. Recently there was a corruption of data due to a rather old version of VirtualDomain that comes with Centos 7 epel-release repo. In this version of VirtualDomain function "VirtualDomain_Validate_All()" call everytime when VirtualDomain script executes. When domain definition files (attr "config") were unavailable, VirtualDomain found that the virtual machine is not running ("Configuration file $OCF_RESKEY_config not readable, resource considered stopped."), but that was not true, and start this VM's on another node. Then I got corruption of data, because multiple instances of VM with shared storage was launched. In master branch of VirtualDomain this bug is absent, but from now I want to control if the virtual machine is running somewhere more before domain start. In my opinion the VirtualDomain does not include this functionality, as well as a set of usecases can be used. I propose to introduce a new attribute "start_scripts" for the domain launch control. After that, the administrator will be able to implement the required functionality through scripts. 

I'm new in github, please see my pull request https://github.com/ClusterLabs/resource-agents/pull/857 and if necessary, add the "start_scripts" attribute to master branch.

**Comment by krig** [comment]
Closing as #857 exists for this issue.
