### ISSUE TITLE
Galera agent doesn't work when grastate.dat contains safe_to_bootstrap

### ISSUE THREAD

**Issue by gyurco** [ClusterLabs/resource-agents#915]
The galera agent doesn't work with the safe-to-bootstrap feature:
http://galeracluster.com/2016/11/introducing-the-safe-to-bootstrap-feature-in-galera-cluster/

A simple fix can be a
````
sed -i 's/^safe_to_bootstrap:.*/safe_to_bootstrap: 1/' ${OCF_RESKEY_datadir}/grastate.dat
````
in galera_start_local_node(), after 'if ocf_is_true $bootstrap; then'

I think it is fairly safe, because it enables bootsrapping for the already detected best node.

**Comment by dciabrin** [comment]
So I'm not familiar with that new flag yet, but your proposal seems to essentially bypass it entirely rather than use it for detecting the bootstrap node.

Have you checked where this flag is stored and used in galera?

My concern with that proposal is that by doing so, we deny the existence of this new "feature", and if that value is also stored elsewhere (e.g. innodb), circumventing it will have bad results. To illustrate my point, "seqno" value is store both in grastate.dat and in innodb (fetchable with mysqld_safe --wsrep-recover).

**Comment by gyurco** [comment]
I'm not aware of any other locations where it is stored. 

I think the existing detection via the --wsrap-recover is good enough. As the above docs says, it is a convenient flag for sysadmins to start the cluster, and the existing methods determining the "best" node still works. And if all nodes marked with "safe_to_bootstrap: 0" by galera, then the proposed change is a must (I've tested it with Percona XtraDB Cluster 5.7).
One can argue, if a node is marked with "safe_to_bootstrap: 1" already, and the found best node is not the same, then what to do.

**Comment by dciabrin** [comment]
> And if all nodes marked with "safe_to_bootstrap: 0" by galera, then the proposed change is a must (I've tested it with Percona XtraDB Cluster 5.7).
Do you recall the condition which triggered that? What is Codership's recommend way to restart the cluster in such condition?

> One can argue, if a node is marked with "safe_to_bootstrap: 1" already, and the found best node is not the same, then what to do.
Suppose there's a network partition impacting all the node, they will go non-primary and the resource agent will shut them down. Will they all have "safe_to_bootstrap: 1" afterwards?

**Comment by gyurco** [comment]
Actually stopping the cluster with the crm_resource command leaves all nodes with "safe_to_bootstrap: 0" for me. In this case, the docs says:
````
In case of a hard crash, all nodes will have safe_to_bootstrap: 0, so we will need to consult the InnoDB storage engine to determine which node has committed the last transaction in the cluster. This is achieved by starting mysqld with the --wsrep-recover variable, which produces an output like this:
````
Which is what the resource agent does.

After a networking partition, the quorum is lost, I think they'll be not safe to bootstrap (safe_to_bootstrap: 0).

**Comment by hoonetorg** [comment]
felt above this problem on qa host of customer a few seconds ago
where should 
```
sed -i 's/^safe_to_bootstrap:.*/safe_to_bootstrap: 1/' ${OCF_RESKEY_datadir}/grastate.dat
```
be inserted to workaround the problem???

**Comment by gyurco** [comment]
in galera_start_local_node(), after 'if ocf_is_true $bootstrap; then'

Or download the version with that from:
https://raw.githubusercontent.com/DoclerLabs/openstack/master/openstack-installer/roles/galera/files/galera-agent

Using this for a while, no problems so far.

**Comment by gyurco** [comment]
Well, I don't think these two issues are related. Detecting the last known sequence number works perfectly without safe_to_bootsrap: 1, just it is impossible to start the first node.

**Comment by acomisario** [comment]
Is this fixed already ? 
If you try to start a galera cluster on ubuntu 16.04 after it was stoped by the resource agent (leaving safe_to_bootstrap: 0) the cluster never starts
